"""Exact Japanese translations for the About page."""

TRANSLATIONS = {
    "About Englishire | Why We Exist": "Englishireについて | 設立の理由",
    "Continuity deserves more than a hurried answer.": "授業の継続には、急場しのぎではない対応が必要です。",
    "Englishire was established to help schools preserve the quiet order of education when circumstances require a temporary change of teacher.": "Englishireは、事情により講師を一時的に替える必要があるときも、学校が落ち着いた教育環境を保てるよう支援するために設立されました。",
    "Our work is shaped by Tokyo classrooms, Japanese learners and a simple conviction: temporary cover should support what a school has carefully built, not oblige it to lower its expectations merely because the timetable has become difficult.": "Englishireの仕事は、東京の教室、日本の学習者、そして一つの明確な考えに基づいています。短期の代講は、学校が丁寧に築いてきたものを支えるべきであり、時間割が難しくなったというだけで教育への期待を下げさせるものであってはなりません。",
    "Every school has its own character. Temporary cover should enter it with care.": "どの学校にも独自の文化があります。短期の代講は、それを尊重して慎重に入るべきです。",
    "Why We Exist": "Englishireを設立した理由",
    "Schools need time to make sound staffing decisions.": "学校が適切な人員判断を行うには、時間が必要です。",
    "Every school develops its own character over time. Its routines become familiar. Its expectations become understood. Pupils recognise the people who greet them, the classrooms in which they learn and the standards which quietly shape each school day.": "学校は時間をかけて独自の文化を築きます。日常の手順が定着し、期待されることが共有されます。生徒は、自分を迎える人、学ぶ教室、毎日の学校生活を静かに形づくる基準を知っています。",
    "A teacher's absence interrupts that continuity. It need not diminish it.": "講師の欠勤はその継続を中断しますが、教育の質まで下げる必要はありません。",
    "Englishire was established from a practical observation. Schools rarely lack goodwill when a staffing difficulty arises. What they lack is time. An absence may require an answer before the first lesson. A recruitment process may take longer than expected. A growing timetable may ask more of the existing team than can reasonably be sustained.": "Englishireは、教育現場での実際の気づきから始まりました。人員の問題が起きたとき、学校に不足しているのは誠意ではなく時間です。欠勤には最初の授業前の回答が必要になり、採用は予定より長引くことがあり、増える時間割が既存の職員に無理な負担を求めることもあります。",
    "Yet the sound permanent decision is seldom the one made in haste. Proper temporary cover gives a school room to think, recruit and plan without allowing the quality of the school day to become the price of that time.": "しかし、常勤人員についての適切な判断が、急いで行った判断であることはほとんどありません。適切な短期代講は、学校の一日の質を犠牲にせずに、考え、採用し、計画する時間を確保します。",
    "The Observation Behind Englishire": "Englishireの出発点となった気づき",
    "The difficulty was never simply finding a teacher.": "問題は、単に講師を見つけることではありませんでした。",
    "The real difficulty was finding the right teacher, with sufficient understanding, in the time available.": "限られた時間の中で、必要な理解を持つ適切な講師を見つけることが本当の難しさでした。",
    "Availability alone does not make a teacher suitable for a classroom. The school, the learners, the timetable, the lesson format, the journey and the responsibilities attached to the assignment all matter.": "予定が空いているだけでは、その講師が教室に適しているとはいえません。学校、学習者、時間割、授業形式、移動条件、担当業務のすべてが関係します。",
    "Englishire grew from the belief that these details should be considered before an assignment is accepted, not discovered after a teacher has arrived. That belief remains the basis of the organisation.": "こうした事項は、講師が到着してから判明するのではなく、ご依頼を引き受ける前に確認すべきだという考えからEnglishireは生まれました。その考えが今も組織の基礎です。",
    "The school is not interchangeable": "学校はどこでも同じではありません",
    "Each organisation has its own culture, routines and reasonable expectations of professional conduct.": "教育機関ごとに、独自の文化、日常の手順、職務上の行動への合理的な期待があります。",
    "The learner is not a timetable entry": "学習者は時間割上の一枠ではありません",
    "Age, confidence, level and prior classroom experience shape how a lesson should be approached.": "年齢、自信、レベル、これまでの授業経験によって、適切な授業の進め方は変わります。",
    "The assignment is not merely a vacancy": "ご依頼は単なる空き時間ではありません",
    "A single day, recurring timetable and extended placement demand different forms of preparation and judgement.": "1日だけの代講、定期的な時間割、長期の短期手配では、それぞれ異なる準備と判断が必要です。",
    "Urgency does not remove responsibility": "急ぎでも責任は変わりません",
    "Indeed, the less time available, the more valuable calm and accurate judgement become.": "むしろ、使える時間が少ないほど、落ち着いた正確な判断が重要になります。",
    "Experience Applied Where It Matters": "必要な場面で経験を生かす",
    "Experience shows in the questions asked before an assignment is accepted.": "経験は、ご依頼を引き受ける前に何を確認するかに表れます。",
    "Reporting time, travel, learner ages, class size, lesson objectives, materials and handover expectations all matter.": "到着時刻、移動条件、学習者の年齢、クラス人数、授業目標、教材、引き継ぎへの期待はすべて重要です。",
    "Englishire's approach has been shaped across the varied landscape of English education in Tokyo: independent language schools, children's programmes, private and international settings, adult classes, specialist courses and other organisations with their own methods and expectations.": "Englishireの考え方は、東京にある多様な英語教育の現場で形づくられてきました。独立系の語学学校、子ども向けプログラム、私立・国際教育環境、成人クラス、専門コースなど、それぞれに独自の方法と期待があります。",
    "That breadth matters because no universal formula can serve every classroom. A lively afternoon class for young children bears little resemblance to an evening programme for working adults. A formal academic setting asks something different of a teacher than a conversational school with a highly personal atmosphere.": "幅広い経験が重要なのは、すべての教室に通用する一つの方法がないからです。幼い子どもの活気ある午後クラスと、社会人向け夜間プログラムでは授業の形が大きく異なります。学術的な環境と、個別性の高い英会話スクールでも、講師に求められることは異なります。",
    "Familiarity with these distinctions does not encourage assumption. Quite the reverse. It teaches one to ask better questions, notice practical risks and recognise when an arrangement which appears straightforward requires closer examination.": "こうした違いを知ることは、思い込みを強めることではありません。むしろ、より適切な質問をし、実務上のリスクに気づき、簡単に見える手配に詳しい確認が必要な場面を見極める助けになります。",
    "Travel, lesson length, preparation time and movement between classes all affect whether an assignment can be undertaken punctually and properly.": "移動、授業時間、準備時間、クラス間の移動は、ご依頼を時間どおり適切に実施できるかに影響します。",
    "Age, confidence, language level, classroom habits and learning purpose influence the manner in which a teacher should enter the room.": "年齢、自信、英語レベル、教室での習慣、学習目的によって、講師が授業に入る際の適切な対応は変わります。",
    "Every organisation has established standards, routines and ways of communicating with pupils, parents and colleagues.": "どの教育機関にも、築かれた基準、日常の手順、生徒・保護者・同僚との連絡方法があります。",
    "The unanswered question is often the detail which determines whether an otherwise sensible arrangement will actually work.": "まだ答えのない一つの質問が、ほかの条件は妥当な手配を実際に実施できるかどうかを決めることがあります。",
    "A capable teacher reads the room as carefully as the lesson plan.": "適切な講師は、授業計画と同じくらい注意深く教室の様子を読み取ります。",
    "Confidence before display": "目立つ発言より、安心して参加できる自信を",
    "Some learners speak readily. Others require time and reassurance before they are willing to take a linguistic risk in public.": "すぐに話す学習者もいれば、人前で英語を試すまでに時間と安心感を必要とする学習者もいます。",
    "Participation should not be measured solely by who speaks first or loudest.": "参加の度合いを、最初に話した人や最も声の大きい人だけで測るべきではありません。",
    "Structure without rigidity": "窮屈にせず、明確な授業構成を",
    "Clear expectations and an orderly lesson often create the security from which genuine participation becomes possible.": "求められることが明確で、授業が秩序立っていると、学習者は安心して本当に参加できるようになります。",
    "Warmth and classroom command are not opposites. Good teaching frequently requires both.": "親しみやすさと適切な授業運営は対立するものではありません。良い授業には、その両方が必要です。",
    "Respect for purpose": "学習目的を尊重する",
    "Continuity with what came before": "これまでの学習を引き継ぐ",
    "A temporary teacher should understand where the class has been, what it is working towards and how the school ordinarily supports progress.": "短期講師は、クラスがこれまで何を学び、何を目指し、学校が通常どのように学習の進展を支えているかを理解する必要があります。",
    "The object is not to perform a disconnected lesson, but to serve the course already in progress.": "前後から切り離された授業を行うのではなく、すでに進んでいるコースを支えることが目的です。",
    "Our Written Standard": "Englishireが明文化した基準",
    "The Standard governs the work in practice.": "この基準を実務に適用します。",
    "is the written expression of how we believe professional teacher cover should be approached. It describes the responsibilities which precede an assignment, the conduct expected during it and the judgement required when circumstances change.": "は、専門的な講師代講をどのように行うべきかというEnglishireの考えを明文化したものです。ご依頼前の責任、担当期間中に求める行動、状況が変わったときに必要な判断を説明します。",
    "It is neither a slogan nor a collection of extravagant promises. It exists so that schools, teachers and Englishire itself may understand the principles against which each decision should be considered.": "スローガンでも、大げさな約束を集めたものでもありません。学校、講師、Englishireが、各判断をどの原則に照らして検討するかを共有するための文書です。",
    "Suitability before availability": "空き状況より適合性を優先する",
    "A free teacher is not necessarily the right teacher.": "予定が空いている講師が、必ずしも適切な講師とは限りません。",
    "Preparation before placement": "配置より先に準備を行う",
    "Professional teaching begins before the classroom door opens.": "専門的な指導は、教室の扉が開く前から始まります。",
    "Continuity before convenience": "利便性より継続性を優先する",
    "The assignment should protect the course already in progress.": "ご依頼は、すでに進んでいるコースの継続を守るべきです。",
    "Honesty before reassurance": "安心させることより、まず正直に伝える",
    "A measured answer is preferable to a promise which cannot be kept.": "守れない約束より、慎重に確認した回答の方が適切です。",
    "Our Responsibility": "Englishireの責任",
    "Trust should be answered with proportionate care.": "託された信頼には、相応の配慮で応えます。",
    "What We Believe": "Englishireが大切にすること",
    "Reasonable principles, consistently applied.": "合理的な原則を、一貫して適用します。",
    "Not grand declarations. Simply the habits required to conduct temporary teacher cover properly.": "大げさな宣言ではありません。短期の講師代講を適切に行うために必要な、日々の実務姿勢です。",
    "Working With Schools": "学校との連携",
    "Schools need not wait for an absence before introducing themselves. A prior understanding of the school, its timetable and the sort of assignment which may one day arise can make future enquiries considerably more straightforward.": "講師が欠勤するまで待たずに、学校についてご連絡いただけます。学校、時間割、将来想定されるご依頼を事前に理解しておくと、今後のお問い合わせをより円滑に検討できます。",
    "Looking Ahead": "今後に向けて",
    "A reputation should be earned quietly.": "信頼は、着実な仕事によって得るものです。",
    "Englishire does not seek to appear larger, louder or more certain than the circumstances justify. We would rather be known for sound judgement, clear communication and work carried out with proper respect for the schools which place confidence in us.": "Englishireは、実際の状況以上に大きく見せたり、強く断言したりしません。適切な判断、明確な連絡、信頼を寄せる学校への敬意を持った仕事によって知られることを目指します。",
    "We hope the organisation becomes known not simply for providing temporary teachers, but for approaching every assignment with the same care, proportion and professional judgement that schools seek to preserve within their own classrooms.": "単に短期講師を提供する組織ではなく、学校が教室で守ろうとしているのと同じ配慮、節度、専門的判断を持って、すべてのご依頼に向き合う組織として信頼されることを目指します。",
    "Standards are seldom maintained by accident. They are maintained by people who choose not to compromise them.": "基準が偶然に守られることはほとんどありません。妥協しないと決めた人々によって守られます。",
    "At Your Service": "ご相談ください",
    "When the timetable requires a capable pair of hands, we should be pleased to hear from you.": "時間割を支える適切な講師が必要なときは、Englishireへご相談ください。",
    "Send the school location, requested dates, lesson times, learner age groups and the nature of the assignment. We will review the requirement with proper care.": "学校所在地、ご希望の日程、授業時間、学習者の年齢層、ご依頼内容をお送りください。必要事項を丁寧に確認します。",
    "Englishire about page actions": "Englishireについてのページ操作",
    "Officials addressing an assembly of schoolchildren outside a civic building": "公共施設の前で、集まった児童に話す関係者",
    "Selected Englishire principles": "Englishireの主な原則",
    "Why Englishire exists: a considered approach to temporary English teacher cover, shaped by Tokyo classrooms, Japanese learners and a belief that continuity should never be treated carelessly.": "Englishireの設立理由。東京の教室と日本の学習者への理解に基づき、授業の継続を決して安易に扱わない英語講師代講の考え方を紹介します。",
    "Englishire was established to help Tokyo schools preserve continuity, exercise sound judgement and maintain standards when circumstances require temporary teacher cover.": "Englishireは、短期の講師代講が必要なときも、東京の学校が授業を継続し、適切に判断し、教育水準を保てるよう支援するために設立されました。",
    "A considered approach to teacher cover, shaped by Tokyo schools, Japanese learners and the practical responsibility of preserving continuity.": "東京の学校と日本の学習者への理解、授業を継続する実務上の責任に基づく、英語講師代講への慎重な考え方です。",
}
