"""Common navigation, footer, interface and structured-data translations."""

TRANSLATIONS = {
    "Temporary English Teacher Cover in Tokyo | Englishire": "東京の学校向け英語講師の代講・短期手配 | Englishire",
    "Temporary English Teacher Cover for Tokyo Schools | Englishire": "東京の学校向け英語講師の代講・短期手配 | Englishire",
    "Temporary English Teacher Cover · Tokyo": "東京都内の学校向け英語講師の代講・短期手配",
    "Temporary Teacher Cover · Tokyo": "東京都内の学校向け英語講師の代講・短期手配",
    "Temporary English Teacher Cover": "英語講師の代講・短期手配",
    "Temporary English teacher cover": "英語講師の代講・短期手配",
    "Temporary teacher cover": "講師の代講・短期手配",
    "Englishire provides considered temporary English teacher cover for schools throughout Tokyo.": "Englishireは、東京都内の学校向けに、ご依頼内容を丁寧に確認したうえで英語講師の代講・短期手配を提供します。",
    "Tokyo, Japan": "東京都",
    "Skip to main content": "本文へ移動",
    "Menu": "メニュー",
    "Teacher Cover": "講師の代講・短期手配",
    "When We Help": "対応できるケース",
    "How It Works": "ご利用の流れ",
    "Journal": "Journal",
    "About": "Englishireについて",
    "Questions": "よくあるご質問",
    "Contact": "お問い合わせ",
    "Request Teacher Cover": "代講について相談する",
    "Request a Teacher": "代講について相談する",
    "Start an Enquiry": "問い合わせる",
    "Start an enquiry": "問い合わせる",
    "Enquiries": "お問い合わせ",
    "Services": "サービス",
    "Privacy": "プライバシー",
    "Privacy Policy": "プライバシーポリシー",
    "Terms": "利用規約",
    "Cookies": "Cookieポリシー",
    "Accessibility": "アクセシビリティ",
    "Editorial Policy": "編集方針",
    "Permissions": "転載・利用許可",
    "Service Standards": "サービス方針",
    "All rights reserved.": "無断転載を禁じます。",
    "Englishire. All rights reserved.": "Englishire. 無断転載を禁じます。",
    "Englishire homepage": "Englishireホームページ",
    "Return to Englishire homepage": "Englishireホームページへ戻る",
    "Primary navigation": "メインナビゲーション",
    "Footer service navigation": "フッターのサービス案内",
    "Footer company navigation": "フッターのEnglishire案内",
    "Considered temporary English teacher cover for Tokyo schools.": "東京の学校を対象に、内容を丁寧に確認したうえで英語講師の代講・短期手配を行います。",
    "For temporary teacher cover, please include the school location, requested dates and lesson schedule.": "英語講師の代講についてお問い合わせの際は、学校所在地、ご希望の日程、授業時間をお知らせください。",
    "For teacher cover enquiries, please include the school location, requested dates and lesson schedule.": "英語講師の代講についてお問い合わせの際は、学校所在地、ご希望の日程、授業時間をお知らせください。",
    "Please include your school location, requested dates and lesson schedule.": "学校所在地、ご希望の日程、授業時間をお知らせください。",
    "This website works best with JavaScript enabled, but all essential service information and links remain available.": "このサイトはJavaScriptを有効にすると快適にご利用いただけますが、主要なサービス情報とリンクはJavaScriptなしでも確認できます。",
    "This website works best with JavaScript enabled, though all essential information and links remain available without it.": "このサイトはJavaScriptを有効にすると快適にご利用いただけますが、主要な情報とリンクはJavaScriptなしでも確認できます。",
    "This website works best with JavaScript enabled. Without JavaScript, the form will be submitted through Formspree and may display its own confirmation page. You may also write to info@englishire.com.": "このサイトはJavaScriptを有効にすると快適にご利用いただけます。JavaScriptが無効の場合、フォームはFormspree経由で送信され、Formspreeの確認画面が表示されることがあります。info@englishire.comへのメールでもお問い合わせいただけます。",
}
