"""Exact Japanese translations for the Contact page."""

TRANSLATIONS = {
    "Request Temporary English Teacher Cover | Englishire": "英語講師の代講・短期手配を相談する | Englishire",
    "Clear teacher cover begins with the right information.": "適切な講師代講は、必要な情報を正確に共有することから始まります。",
    "Whether cover is needed tomorrow morning or planned for a future date, we welcome your enquiry.": "明日の朝に代講が必要な場合も、先の日程を計画している場合も、お問い合わせください。",
    "Provide the details currently available, including dates, lesson times, location and learner information. We will review the assignment individually before confirming suitable cover.": "日程、授業時間、所在地、学習者情報など、現時点で分かる内容をお知らせください。適切な代講を確定する前に、ご依頼を個別に確認します。",
    "Complete the Enquiry Form": "お問い合わせフォームへ",
    "A telephone operator works at a historic airport switchboard. The image reflects the value of precise information when a timely response is needed.": "歴史ある空港の交換台で電話交換手が業務を行っています。迅速な対応が必要なときほど、正確な情報が重要であることを表す写真です。",
    "Information to Include": "お知らせいただきたい情報",
    "Give us the facts needed to assess the assignment.": "ご依頼を検討するために必要な事実をお知らせください。",
    "A concise outline of the school, timetable, learners and work required is enough to begin.": "学校、時間割、学習者、必要な業務について簡潔にお知らせいただければ、検討を始められます。",
    "Urgent circumstances do not always allow every detail to be known at once. Send the information currently available and identify what remains to be confirmed.": "急ぎの場合、すべての情報がすぐに分からないこともあります。現時点で分かる内容を送り、未確認の点を明記してください。",
    "Complete information helps us assess availability, suitability and travel practicalities without unnecessary delay.": "情報がそろっているほど、講師の空き状況、適合性、移動条件を不要な遅れなく確認できます。",
    "Sending an enquiry begins the review process. Cover is confirmed only after Englishire has agreed the assignment.": "お問い合わせを送ると検討が始まります。Englishireがご依頼内容を確認し、明確に合意した後に代講が確定します。",
    "Teacher Cover Enquiry": "英語講師の代講に関するお問い合わせ",
    "Request temporary English teacher cover.": "英語講師の代講・短期手配をご相談ください。",
    "Fields marked with an asterisk are required before your enquiry can be submitted securely.": "アスタリスク（*）の付いた項目は必須です。",
    "Leave this field empty": "この項目には入力しないでください",
    "Your enquiry will be transmitted securely to Englishire when you select “Send Enquiry”.": "「お問い合わせを送信」を選ぶと、入力内容がEnglishireへ安全に送信されます。",
    "Contact name *": "ご担当者名 *",
    "Contact email *": "ご担当者のメールアドレス *",
    "School name *": "学校名 *",
    "School location *": "学校所在地 *",
    "Nearest station": "最寄り駅",
    "Requested dates *": "ご希望の日程 *",
    "For example, 12–16 October 2026.": "例：2026年10月12日〜16日",
    "Lesson times *": "授業時間・時間割 *",
    "Learner ages and class sizes *": "学習者の年齢・クラス人数 *",
    "Lesson type and objectives *": "授業形式・学習目標 *",
    "Materials provided": "学校で用意する教材",
    "Arrival and reporting instructions": "来校・受付・報告方法",
    "Special requirements": "その他のご要望・注意事項",
    "This is an urgent enquiry.": "急ぎのご相談です。",
    "Send Enquiry": "お問い合わせを送信",
    "Prefer to write the email yourself?": "メールで直接問い合わせる場合",
    "For temporary teacher cover enquiries, please email Englishire directly.": "英語講師の代講について、Englishireへ直接メールでお問い合わせいただけます。",
    "Please include the school location, requested dates, lesson times, learner age groups and the nature of the assignment.": "学校所在地、ご希望の日程、授業時間、学習者の年齢層、ご依頼内容をお知らせください。",
    "Assignment Checklist": "送信前の確認事項",
    "Check that the essential details are included.": "必要な情報が含まれているかご確認ください。",
    "School name and location": "学校名・所在地",
    "Dates and lesson times": "日程・授業時間",
    "Learner ages and class sizes": "学習者の年齢・クラス人数",
    "Lesson type and objectives": "授業形式・学習目標",
    "Materials provided": "学校で用意する教材",
    "Arrival and reporting instructions": "来校・受付・報告方法",
    "Any special requirements": "その他のご要望・注意事項",
    "Urgent Enquiries": "急ぎのご相談",
    "Send the confirmed details first.": "まず、確認できている情報をお送りください。",
    "If the requirement is urgent and certain details remain uncertain, send the available information and identify what still requires confirmation.": "急ぎで、一部の情報がまだ分からない場合は、現時点で分かる内容を送り、未確認の点を明記してください。",
    "Confirmation and Availability": "手配の確定と空き状況",
    "An enquiry is reviewed before cover is confirmed.": "代講を確定する前に、お問い合わせ内容を確認します。",
    "Teacher cover cannot be confirmed until the assignment has been reviewed and both suitability and availability have been established.": "ご依頼内容を確認し、講師の適合性と空き状況の両方を確認するまでは、代講を確定できません。",
    "Common Enquiry Questions": "お問い合わせに関するよくあるご質問",
    "Answers to common questions about submitting an enquiry.": "お問い合わせの送信について、よくある質問にお答えします。",
    "These answers concern the enquiry itself. The full questions page contains further information about temporary teacher cover.": "ここではお問い合わせ手続きについて説明します。英語講師の代講・短期手配全体については、よくあるご質問のページをご覧ください。",
    "What if the timetable is not yet final?": "時間割がまだ確定していない場合はどうすればよいですか？",
    "Provide the current version and make clear that it remains provisional. Any material change must be reviewed before cover can be confirmed.": "現在の時間割を送り、暫定版であることを明記してください。重要な変更がある場合は、代講の確定前に改めて確認します。",
    "May we send supporting documents separately?": "関連資料を別に送ることはできますか？",
    "Yes. Timetables, lesson plans, school maps and other useful documents may be supplied after the initial enquiry, subject to the communication arrangements provided in our response.": "はい。時間割、授業計画、学校案内図などの資料は、最初のお問い合わせ後に、Englishireからご案内する方法で送付できます。",
    "Does sending an enquiry reserve a teacher?": "問い合わせを送ると講師を確保できますか？",
    "No. Sending an enquiry begins the review process. A teacher is reserved only after Englishire has reviewed and expressly confirmed the assignment.": "いいえ。お問い合わせを送ると検討が始まります。Englishireが内容を確認し、明確に手配を確定した後に講師を確保します。",
    "Can we enquire before the need becomes urgent?": "急ぎになる前に問い合わせてもよいですか？",
    "Yes. Advance introductions are welcome and can make a future request easier to assess.": "はい。事前に学校について共有していただくと、将来のご依頼をより円滑に検討できます。",
    "What Happens Next": "お問い合わせ後の流れ",
    "We will review the assignment and explain the next step.": "ご依頼内容を確認し、次の手順をご説明します。",
    "Our response will address any questions, availability and the practical steps required before cover can be confirmed.": "ご質問への回答、講師の空き状況、代講を確定する前に必要な実務手順をお伝えします。",
    "Return to the Form": "フォームへ戻る",
    "Contact page actions": "お問い合わせページの操作",
    "A telephone operator working at a historic airport switchboard": "歴史ある空港の交換台で業務を行う電話交換手",
    "Request temporary English teacher cover for your school in Tokyo. Send Englishire the timetable, location, learner and lesson details required to review the assignment properly.": "東京の学校向け英語講師の代講・短期手配をご相談ください。時間割、所在地、学習者、授業内容をお送りいただき、Englishireがご依頼を適切に確認します。",
    "Send Englishire the details of your school, timetable and temporary English teacher cover requirement.": "学校の概要、時間割、必要な英語講師の代講・短期手配についてEnglishireへお知らせください。",
    "A considered enquiry form for temporary English teacher cover in Tokyo.": "東京の学校向け英語講師代講を、必要事項に基づいて丁寧に検討するためのお問い合わせフォームです。",
}
