"""Exact Japanese translations for the Cookie Policy."""

TRANSLATIONS = {
    "Small technologies deserve a clear explanation.": "Cookieなどの小さな技術についても、明確に説明します。",
    "This page explains the cookies and similar technologies which may help the Englishire website function properly.": "このページでは、Englishireのウェブサイトを適切に機能させるために使用する可能性のあるCookieと類似技術を説明します。",
    "Cookies need not be mysterious. They are simply small pieces of information used by websites and browsers for purposes such as security, preferences, forms and basic measurement.": "Cookieは難しく考える必要はありません。ウェブサイトとブラウザが、安全管理、設定の記憶、フォーム、基本的な利用状況の把握などに使う小さな情報です。",
    "16 July 2026": "2026年7月16日",
    "Transparency is not achieved by providing more words. It is achieved by providing the right ones.": "透明性は、言葉を増やすことではなく、必要なことを正確に説明することで得られます。",
    "The Straightforward Explanation": "分かりやすい説明",
    "The website should use only what it has a reason to use.": "ウェブサイトは、明確な理由がある技術だけを使用するべきです。",
    "Some cookies are essential because a website cannot operate sensibly without them. Others may be used to remember a choice, understand basic usage or support a service provided by another organisation.": "ウェブサイトの基本動作に欠かせないCookieがあります。ほかに、選択内容の記憶、基本的な利用状況の把握、他社が提供するサービスの支援に使われるCookieもあります。",
    "Englishire does not regard the existence of a technology as a sufficient reason to deploy it. Non-essential tools should be used only where they serve a clear purpose.": "Englishireは、技術が存在するというだけでは導入の十分な理由にならないと考えています。必須でないツールは、明確な目的がある場合だけ使用するべきです。",
    "Necessity should come before convenience.": "利便性より必要性を優先します。",
    "What this policy covers": "本ポリシーの項目",
    "1. What cookies are": "1. Cookieとは",
    "2. Essential cookies": "2. 必須Cookie",
    "3. Preference cookies": "3. 設定Cookie",
    "4. Performance and analytics": "4. パフォーマンスとアクセス解析",
    "5. Third-party services": "5. 第三者サービス",
    "6. Managing cookies": "6. Cookieの管理",
    "7. Current use on this website": "7. 現在のサイトでの利用状況",
    "8. Privacy": "8. プライバシー",
    "9. Changes": "9. 変更",
    "10. Contact": "10. お問い合わせ",
    "What cookies are": "Cookieとは",
    "A cookie is a small text file which a website may ask a browser to store on a computer, telephone or other device.": "Cookieとは、ウェブサイトがブラウザに依頼して、パソコン、スマートフォン、その他の端末に保存することがある小さなテキストファイルです。",
    "Cookies can help a website remember information between pages or visits. Similar technologies may perform related functions without using a traditional cookie file.": "Cookieを使うと、ページ間や再訪時に情報を記憶できます。従来のCookieファイルを使わずに、同様の機能を果たす技術もあります。",
    "A cookie is not, by itself, a programme and cannot read every file on a device. Its significance depends upon the information placed within it and the purpose for which it is used.": "Cookie自体はプログラムではなく、端末内のすべてのファイルを読み取るものでもありません。どの情報を入れ、何の目的で使うかによって意味が変わります。",
    "Essential cookies": "必須Cookie",
    "Essential cookies are used where the website requires them for basic operation, security or a function requested by the visitor.": "必須Cookieは、サイトの基本動作、安全管理、または利用者が求めた機能に必要な場合に使用されます。",
    "They may, for example, assist with:": "たとえば、次の目的に使われることがあります。",
    "secure and reliable page delivery;": "安全で安定したページ表示",
    "fraud, abuse or security protection;": "不正、悪用、セキュリティ上の問題からの保護",
    "remembering a temporary form or session state;": "一時的なフォーム入力やセッション状態の記憶",
    "maintaining basic website preferences;": "基本的なサイト設定の維持",
    "supporting a cookie-choice mechanism itself.": "Cookieの選択機能自体の動作",
    "Because these technologies support the service requested by the visitor, the website may not function properly if they are blocked.": "これらの技術は利用者が求めたサービスを支えるため、ブロックするとサイトの一部が正しく動作しないことがあります。",
    "Preference cookies": "設定Cookie",
    "Preference cookies may remember a choice such as language, display setting, accessibility preference or another option selected by the visitor.": "設定Cookieは、言語、表示、アクセシビリティ、その他の利用者が選んだ設定を記憶する場合があります。",
    "Englishire should use such cookies only where a remembered choice provides a genuine benefit rather than merely adding complexity.": "Englishireは、仕組みを複雑にするだけでなく、選択内容を記憶することに実際の利点がある場合だけ、このようなCookieを使用するべきだと考えています。",
    "Performance and analytics": "パフォーマンスとアクセス解析",
    "Analytics technologies may help a website understand broad usage patterns, such as which pages are visited, whether visitors encounter technical difficulties and how the site might be made clearer or more useful.": "アクセス解析技術を使うと、閲覧されるページ、技術的な問題の発生、サイトをより分かりやすく有用にする方法など、全体的な利用傾向を把握できる場合があります。",
    "If Englishire introduces non-essential analytics, the relevant service should be identified, the purpose should be explained and an appropriate choice or consent mechanism should be provided where required.": "Englishireが必須でないアクセス解析を導入する場合は、利用するサービスを明示し、目的を説明し、必要に応じて適切な選択または同意の仕組みを提供します。",
    "Analytics should not be described as anonymous where the technology or provider can reasonably associate the information with an individual, device or account.": "利用する技術や提供者が情報を個人、端末、アカウントと合理的に結びつけられる場合、その解析を匿名と説明するべきではありません。",
    "Third-party services": "第三者サービス",
    "Some website functions may be supplied by other organisations, such as hosting providers, form services, embedded media, security tools or analytics providers.": "サイトの一部機能は、ホスティング事業者、フォームサービス、埋め込みメディア、安全管理ツール、アクセス解析事業者など、他の組織が提供する場合があります。",
    "Those services may set their own cookies or receive technical information when their content or function is used.": "そのコンテンツや機能を利用した際に、それらのサービスが独自のCookieを設定したり、技術情報を受け取ったりする場合があります。",
    "Englishire should identify material third-party tools within this policy or an accompanying cookie notice when they are introduced. The provider's own terms and privacy information may also apply.": "重要な第三者ツールを導入する場合、Englishireは本ポリシーまたは付随するCookie通知で明示します。提供者自身の利用条件とプライバシー情報も適用される場合があります。",
    "Managing cookies": "Cookieの管理",
    "Most browsers allow cookies to be viewed, deleted or blocked. The precise controls differ between browsers and devices.": "多くのブラウザでは、Cookieの確認、削除、ブロックができます。具体的な操作方法はブラウザと端末によって異なります。",
    "Visitors may also be presented with an Englishire cookie choice panel where non-essential technologies require a decision.": "必須でない技術について選択が必要な場合、EnglishireのCookie選択画面を表示することがあります。",
    "Refusing non-essential cookies should not prevent access to the ordinary informational pages of the website. Blocking essential cookies, however, may affect forms, security or other requested functions.": "必須でないCookieを拒否しても、通常の情報ページは閲覧できるようにするべきです。ただし、必須Cookieをブロックすると、フォーム、安全管理、その他の求めた機能に影響する場合があります。",
    "Current use on this website": "現在のサイトでの利用状況",
    "At the review date shown above, the website code supplied by Englishire does not set cookies or use browser storage. It does not include analytics, advertising trackers or embedded third-party media.": "上記の確認日時点で、Englishireが提供するサイトコードはCookieを設定せず、ブラウザ保存機能も使用していません。アクセス解析、広告トラッカー、第三者メディアの埋め込みも含まれていません。",
    "The enquiry form prepares a message in the visitor's own email application. The website itself does not transmit or store the form entries.": "お問い合わせフォームは、利用者自身のメールアプリで送信するメッセージを作成します。ウェブサイト自体はフォームの入力内容を送信または保存しません。",
    "A hosting provider may keep ordinary server access logs. If Englishire later introduces cookies, analytics, embedded media or another service, this policy and any required consent controls should be updated before that technology is enabled.": "ホスティング事業者が通常のサーバーアクセスログを保管する場合があります。今後EnglishireがCookie、アクセス解析、埋め込みメディア、その他のサービスを導入する場合は、その技術を有効にする前に本ポリシーと必要な同意機能を更新します。",
    "Cookies form part of the wider manner in which information may be handled through the website.": "Cookieは、ウェブサイトを通じた情報の取扱い全体の一部です。",
    "The": "",
    "explains the types of information Englishire may receive, the purposes for which it may be used and the choices available to individuals.": "では、Englishireが受け取る可能性のある情報、利用目的、ご本人が行える選択を説明しています。",
    "Changes to this policy": "本ポリシーの変更",
    "This policy may be revised when the website, its service providers, its technology or applicable requirements change.": "ウェブサイト、サービス提供者、技術、適用される要件が変わった場合、本ポリシーを改定することがあります。",
    "The review date at the top of the page should be updated when a meaningful change is made.": "重要な変更を行った場合は、ページ上部の確認日を更新します。",
    "Questions concerning cookies, website technology or privacy may be sent through the Englishire": "Cookie、ウェブサイト技術、プライバシーに関するご質問は、Englishireの",
    "Please include enough information to identify the matter you wish us to consider.": "確認を希望する内容を特定できるだけの情報をお知らせください。",
    "COOKIES": "COOKIES",
    "Necessary where useful. Explained where present.": "必要な場合だけ使用し、使用する場合は説明します。",
    "A Final Note": "最後に",
    "The smallest details should still be handled openly.": "小さな技術についても、取扱いを明らかにします。",
    "Englishire believes that technical language should clarify rather than obscure. Where a technology is used, its purpose should be understood.": "Englishireは、専門用語は分かりにくくするためではなく、明確にするために使うべきだと考えています。技術を使用する場合は、その目的が理解できるようにします。",
    "Should you have a question concerning cookies or privacy, we should be pleased to consider it directly.": "Cookieやプライバシーについてご質問がある場合は、個別に確認します。",
    "Questions concerning cookies or privacy may be sent through the contact page.": "Cookieまたはプライバシーに関するご質問は、お問い合わせページからお送りください。",
    "This website works best with JavaScript enabled, though the complete Cookie Policy and every essential link remain available without it.": "このサイトはJavaScriptを有効にすると快適にご利用いただけますが、Cookieポリシー全文と主要なリンクはJavaScriptなしでも確認できます。",
    "A quiet desk with a notebook and carefully arranged correspondence": "ノートと書類が整えられた静かな机",
    "Cookie Policy sections": "Cookieポリシーの項目",
    "Englishire's Cookie Policy explains the small technologies which may help the website function, remember preferences and understand basic usage.": "EnglishireのCookieポリシーは、サイトの動作、設定の記憶、基本的な利用状況の把握に使われる可能性のある技術を説明します。",
    "A clear explanation of the cookies and similar technologies which may be used on the Englishire website.": "Englishireのウェブサイトで使用する可能性のあるCookieと類似技術を分かりやすく説明します。",
    "How Englishire may use cookies and similar technologies.": "EnglishireがCookieと類似技術を使用する可能性について説明します。",
}
