"""Exact Japanese translations for the English homepage."""

TRANSLATIONS = {
    "Established in Tokyo to Support Schools When They Need It Most": "学校が最も支援を必要とするときに応えるため、東京で始まりました",
    "Temporary English teacher cover for schools across Tokyo.": "東京都内の学校向けに、英語講師の代講・短期手配を行います。",
    "Thoughtfully matched, properly briefed and arranged around the school day.": "学校の一日の流れに合わせ、適任性を見極め、必要な事前説明を行ったうえで手配します。",
    "Englishire supports schools facing staff absence, recruitment gaps, timetable changes and additional demand. Tell us what the school needs, and we will review the timetable, location, learners and teaching responsibilities before confirming what can be provided.": "Englishireは、講師の欠勤、採用までの空白期間、時間割の変更、授業数の増加などに直面する学校を支援します。学校が必要としている内容をお知らせください。時間割、所在地、学習者、担当する授業や業務を確認したうえで、対応できる内容をお伝えします。",
    "See How It Works": "ご利用の流れを見る",
    "Read About Teacher Cover": "講師の代講・短期手配について見る",
    "One day or longer": "1日から長期間まで",
    "Cover may be brief, recurring or extended.": "1日だけの代講、毎週の定期的な代講、長期の短期手配に対応します。",
    "Tokyo realities considered": "東京での実務条件を確認",
    "Travel, reporting times, learners and teaching environments considered together.": "移動経路、到着時刻、学習者、授業環境をまとめて確認します。",
    "Properly reviewed": "内容を確認してから確定",
    "No assignment is promised before its requirements are understood.": "必要事項を把握する前に、ご依頼を確約することはありません。",
    "A teacher leads a classroom lesson. The image reflects Englishire’s purpose: to preserve the rhythm of the school day when the usual teacher cannot be there.": "講師が教室で授業を進めています。いつもの講師が不在でも、学校の一日の流れを保つというEnglishireの目的を表す写真です。",
    "Why Temporary Cover Matters": "なぜ短期の代講が必要なのか",
    "Keep the school day moving while the longer-term staffing need is resolved.": "長期的な人員課題を検討している間も、学校の一日を止めないために。",
    "A teacher becomes unwell. A new appointment takes rather longer than expected. A timetable expands before permanent staffing is ready. The pupils still arrive, parents still expect a proper lesson and the school must still conduct its day with composure.": "講師が体調を崩すことがあります。新しい講師の採用が予定より長引くこともあります。常勤体制が整う前に授業数が増えることもあります。それでも生徒は登校し、保護者は通常どおりの授業を期待し、学校は落ち着いて一日を運営しなければなりません。",
    "Englishire gives schools time to address the longer-term staffing need carefully, without treating tomorrow's lesson as an excuse for a hurried permanent decision.": "Englishireの短期手配は、明日の授業を理由に常勤採用を急ぐのではなく、学校が長期的な人員体制を慎重に検討するための時間を確保します。",
    "Temporary cover should relieve pressure without lowering standards.": "短期の代講は、教育の質を下げずに学校の負担を軽減するものであるべきです。",
    "When Englishire Steps In": "Englishireが支援する場面",
    "Staffing difficulties seldom arrive at a convenient hour.": "人員の問題は、都合のよいタイミングで起こるとは限りません。",
    "Englishire assists when absence, delay or changing demand disrupts a carefully arranged timetable.": "欠勤、採用の遅れ、授業需要の変化によって組まれた時間割に支障が出るとき、Englishireが支援します。",
    "Unexpected Absence": "突然の欠勤",
    "A member of staff is unavailable and the first lesson is already approaching.": "担当講師が出勤できず、最初の授業が迫っている場合。",
    "Urgent circumstances may be considered without pretending that urgency removes the need for judgement.": "急ぎのご相談にも対応を検討しますが、緊急であっても必要な確認と判断は省きません。",
    "Between Appointments": "採用の切り替え期間",
    "The previous teacher has departed and the right permanent appointment has not yet been made.": "前任講師が退職し、適切な常勤講師の採用がまだ決まっていない場合。",
    "Temporary cover gives the school room to recruit carefully rather than appoint merely because Monday is approaching.": "短期の代講を利用することで、週明けが迫っているという理由だけで採用を急がず、適切な候補者を慎重に選ぶ時間を確保できます。",
    "Additional Capacity": "授業数の増加への対応",
    "New classes, seasonal programmes or timetable changes have created more teaching hours than expected.": "新しいクラス、季節講座、時間割の変更により、想定より多くの授業時間が必要になった場合。",
    "Temporary support allows the school to decide whether the demand is seasonal, developing or permanent.": "短期の支援を利用しながら、その需要が季節的なものか、増加途中なのか、恒常的なものかを学校が見極められます。",
    "Trials, Events and Limited Programmes": "体験授業・イベント・期間限定講座",
    "A school may require a teacher for a demonstration lesson, event, intensive course or other defined period.": "体験授業、イベント、集中講座など、期間を限定して講師が必要になる場合。",
    "Not every short requirement should become a permanent recruitment exercise.": "短期間の必要に対して、必ずしも常勤採用を行う必要はありません。",
    "Read About Every Cover Situation": "代講を利用できる場面を見る",
    "Designed Around the Actual School": "実際の学校運営に合わせた手配",
    "The assignment must be understood before it is accepted.": "ご依頼を引き受ける前に、内容を正確に把握します。",
    "Every school has its own rhythm. Before confirmation, Englishire considers the timetable, learner ages, class format, lesson expectations, location, travel and the standards by which the school conducts itself.": "学校ごとに、一日の流れや授業の進め方は異なります。確定前に、時間割、学習者の年齢、クラス形式、授業内容、所在地、移動条件、学校の運営方針を確認します。",
    "The object is not to send whoever happens to be free. It is to provide sensible temporary support for the classroom the school actually runs.": "たまたま予定が空いている講師を送ることが目的ではありません。学校が実際に行っている授業に合った、適切な短期支援を提供することが目的です。",
    "Possible duration": "対応期間",
    "One day, several days, recurring weekly cover or a longer temporary period.": "1日、数日間、毎週の定期代講、またはより長い短期手配。",
    "Possible settings": "対象となる教育機関",
    "English schools, academies, private and international programmes and related education providers.": "英会話スクール、各種アカデミー、私立・国際教育プログラム、その他の教育機関。",
    "Possible age groups": "対象となる年齢層",
    "Children, teenagers and adults, depending upon suitability and assignment requirements.": "ご依頼内容と講師の適合性に応じて、子ども、中高生、成人に対応します。",
    "Possible lesson types": "対象となる授業形式",
    "Group classes, private lessons, conversation classes, trials and special programmes.": "グループレッスン、個人レッスン、英会話、体験授業、特別講座。",
    "Read the Full Teacher Cover Page": "講師の代講・短期手配について詳しく見る",
    "Precise.": "正確に。",
    "Judgement before assurance.": "確約より先に、適切な判断を。",
    "Our Governing Principle": "Englishireの基本原則",
    "Every assignment deserves proper consideration before a promise is made.": "どのご依頼も、確約する前に十分な確認と検討が必要です。",
    "A school should receive an answer founded upon the actual timetable, learners, location, lesson expectations and nature of the work—not upon haste or convenience.": "学校への回答は、急ぎや都合ではなく、実際の時間割、学習者、所在地、授業内容、担当業務に基づくべきです。",
    "The full document explains the principles by which suitability, preparation, professional conduct and communication are considered.": "全文では、講師の適合性、事前準備、職務上の行動、連絡方法を判断するための原則を説明しています。",
    "Read The Englishire Standard": "Englishireの基準を読む",
    "A clear process, from enquiry to handover.": "お問い合わせから引き継ぎまで、明確な流れで進めます。",
    "A straightforward sequence, with no promise made ahead of proper consideration.": "必要事項を確認する前に確約せず、順を追って手配を進めます。",
    "The School Explains the Requirement": "学校から必要事項を共有",
    "Location, dates, timetable, learner groups and the reason cover is required.": "所在地、日程、時間割、学習者の年齢層、代講が必要な理由をお知らせください。",
    "The Assignment Is Reviewed": "ご依頼内容を確認",
    "The requirement is considered as a whole rather than as an empty space in a diary.": "単に予定の空きを埋めるのではなく、ご依頼全体を確認します。",
    "Suitability and Availability Are Considered": "適合性と空き状況を確認",
    "A teacher must be free, certainly, but also appropriate for the school and learners.": "講師の予定が空いていることに加え、その学校と学習者に適していることが必要です。",
    "The Arrangement Is Confirmed and Prepared": "手配を確定し、事前準備を実施",
    "The teacher receives the timetable, lesson information and school procedures required for a dependable arrival.": "講師には、時間割、授業情報、到着・受付を含む学校の手順を事前に共有します。",
    "Read the Full Process": "詳しいご利用の流れを見る",
    "From Englishire Journal": "Englishire Journalより",
    "Thoughtful schools deserve thoughtful writing.": "学校運営を真剣に考える方へ、丁寧に書かれた論考を。",
    "Three essays from the present collection, selected for readers encountering the Journal for the first time.": "Englishire Journalを初めて読む方に向けて、現在のコレクションから3本の論考を選びました。",
    "Featured Essay · The Industry": "注目の論考・業界",
    "The End of the Easy Teacher": "The End of the Easy Teacher",
    "How Japan's English schools spent decades mistaking a desire to come to Japan for a desire to teach—and why that assumption no longer holds.": "日本の英語教育業界は長年、「日本に来たい」という希望を「教えたい」という意欲と取り違えてきました。その前提が、なぜ今では成り立たないのかを考察します。",
    "Read the essay": "論考を読む",
    "Essay · School Operations": "論考・学校運営",
    "How Schools Can Handle Staff Shortages": "How Schools Can Handle Staff Shortages",
    "Why a staffing gap rarely remains confined to one classroom, and what separates schools that recover calmly from those that scramble.": "人員不足が一つの教室だけの問題では終わらない理由と、落ち着いて立て直せる学校と混乱する学校の違いを考えます。",
    "Case Study · Leadership": "ケーススタディ・経営",
    "School Collapse After Three Decades": "School Collapse After Three Decades",
    "How an unresolved staff conflict, management inaction and a sequence of preventable failures helped close a long-standing Tokyo school.": "解決されない職員間の対立、経営側の不作為、防ぐことのできた失敗の積み重ねが、東京で長年続いた学校の閉鎖につながった経緯を検証します。",
    "Read the case study": "ケーススタディを読む",
    "The Journal is a genuine editorial publication devoted to school continuity, staffing, leadership and the practical life of English education in Japan.": "Englishire Journalは、学校運営の継続、人員体制、リーダーシップ、日本の英語教育の実務を扱う編集出版物です。",
    "Enter Englishire Journal": "Englishire Journalを読む",
    "Refined.": "節度をもって。",
    "English in manner. Tokyo in understanding.": "姿勢は英国らしく。理解は東京に深く根ざして。",
    "About Englishire": "Englishireについて",
    "A proper understanding of the classroom.": "実際の教室を理解することから。",
    "Englishire provides temporary English teacher cover for schools throughout Tokyo. The work is shaped by substantial experience across the city's broad range of English-learning environments.": "Englishireは、東京都内の学校向けに英語講師の代講・短期手配を提供しています。東京にある多様な英語教育の現場で培った経験を、手配と授業支援に生かしています。",
    "The manner is measured, courteous and properly prepared. The understanding is thoroughly Tokyo: schools, timetables, learners, travel and the practical realities of the day.": "対応は落ち着いて丁寧に行い、必要な準備を整えます。学校、時間割、学習者、移動、当日の実務など、東京の教育現場を具体的に理解したうえで対応します。",
    "Read About Englishire": "Englishireについて詳しく見る",
    "Questions Before the Enquiry": "お問い合わせ前によくあるご質問",
    "Clear answers before a school is asked to decide.": "学校が判断する前に、必要な情報を明確にお伝えします。",
    "A small selection from the full Questions reference.": "よくあるご質問から一部をご紹介します。",
    "How much notice does Englishire require?": "どのくらい前までに連絡すればよいですか？",
    "More notice generally provides more options, though urgent enquiries are welcome. Availability depends upon the dates, times, location and nature of the assignment.": "早めにご連絡いただくほど、対応できる選択肢は増えます。急ぎのご相談も受け付けていますが、対応可否は日程、時間、所在地、ご依頼内容によって異なります。",
    "Can a teacher cover just one day?": "1日だけの代講も依頼できますか？",
    "Yes. An assignment may concern a single day, recurring weekly cover or a longer temporary placement.": "はい。1日だけの代講、毎週の定期代講、より長い期間の短期手配を検討できます。",
    "Does making contact guarantee cover?": "問い合わせれば、必ず講師を手配できますか？",
    "No. Every assignment must be reviewed before it can be confirmed.": "いいえ。ご依頼内容を確認し、適切に対応できると判断した後に手配を確定します。",
    "What information should a school provide?": "学校からどのような情報を伝えればよいですか？",
    "Please include the location, dates, timetable, learner ages, class sizes, lesson format and any particular requirements.": "所在地、日程、時間割、学習者の年齢、クラス人数、授業形式、その他のご要望をお知らせください。",
    "Read All Questions": "よくあるご質問をすべて見る",
    "Before It Becomes Urgent": "急ぎになる前に",
    "A sensible introduction is preferable to a frantic first conversation.": "緊急時に慌てて初めて連絡するより、事前に学校について共有していただく方が、適切な対応につながります。",
    "Schools are welcome to introduce themselves before an urgent need arises. A prior understanding of the school, its timetable and the sort of cover it may require can make a future request easier to assess.": "代講が急に必要になる前でも、学校についてご連絡いただけます。学校の特徴、時間割、将来必要になり得る代講の内容を事前に把握しておくと、実際のご依頼をより速く正確に検討できます。",
    "Tell us about your school, its timetable and the temporary support it may require in future.": "学校の概要、時間割、今後必要になる可能性のある短期支援についてお知らせください。",
    "Introduce Your School": "学校について知らせる",
    "Teacher Cover Enquiries": "英語講師の代講に関するお問い合わせ",
    "When the timetable needs dependable cover, tell us what the school requires.": "時間割を確実に維持するための代講が必要なときは、学校が必要としている内容をお知らせください。",
    "Send the school location, requested dates, lesson times, learner age groups and the nature of the assignment.": "学校所在地、ご希望の日程、授業時間、学習者の年齢層、ご依頼内容をお送りください。",
    "Read the Questions": "よくあるご質問を見る",
    "Englishire service actions": "Englishireのサービス操作",
    "Englishire service summary": "Englishireのサービス概要",
    "English teacher leading a classroom lesson": "教室で授業を進める英語講師",
    "Editorial image for The End of the Easy Teacher": "The End of the Easy Teacherの編集用画像",
    "Editorial image for How Schools Can Handle Staff Shortages": "How Schools Can Handle Staff Shortagesの編集用画像",
    "Editorial image for the school collapse case study": "学校閉鎖のケーススタディ用画像",
    "Englishire provides considered temporary English teacher cover for schools throughout Tokyo, supported by a clear professional process and Englishire Journal.": "Englishireは、明確な手続きと専門的な判断に基づき、東京都内の学校へ英語講師の代講・短期手配を提供しています。Englishire Journalでは、学校運営と英語教育の実務を発信しています。",
    "Considered temporary English teacher cover for Tokyo schools, with clear process, measured judgement and thoughtful writing on school continuity.": "明確な手続きと慎重な判断に基づく、東京の学校向け英語講師の代講・短期手配。学校運営の継続について考えるEnglishire Journalも掲載しています。",
    "Englishire temporary English teacher cover for Tokyo schools": "東京の学校向けEnglishire英語講師代講サービス",
    "Considered temporary English teacher cover for Tokyo schools, with proper attention to the school, the learners and the assignment.": "学校、学習者、ご依頼内容を丁寧に確認して行う、東京の学校向け英語講師の代講・短期手配です。",
}
