"""Exact Japanese translations for the How It Works page."""

TRANSLATIONS = {
    "How Teacher Cover Works in Tokyo | Englishire": "東京の学校向け英語講師代講のご利用の流れ | Englishire",
    "A clear process from first enquiry to final handover.": "最初のお問い合わせから最終の引き継ぎまで、明確な手順で進めます。",
    "Schools should know what happens before cover begins.": "代講が始まる前に何が行われるのかを、学校に明確にお伝えします。",
    "Englishire approaches temporary teacher cover through a clear sequence of enquiry, review, confirmation, preparation, teaching and follow-up. Each stage exists to remove uncertainty before it reaches the classroom.": "Englishireでは、お問い合わせ、内容確認、確定、事前準備、授業、授業後の確認という順序で短期の代講を進めます。教室に不明点を持ち込まないために、それぞれの段階を設けています。",
    "Follow the Process": "手順を見る",
    "Assignment details first": "まずご依頼内容を確認",
    "The assignment is read before availability is discussed.": "講師の空き状況を確認する前に、ご依頼内容を読み、必要事項を把握します。",
    "Confirmation with clarity": "条件を明確にして確定",
    "Nothing is treated as agreed until it has been expressly confirmed.": "明確な確定連絡があるまでは、合意済みとは扱いません。",
    "Preparation before arrival": "到着前に準備",
    "The teacher should understand the school before entering the lesson.": "講師は授業に入る前に、学校と担当内容を理解しておく必要があります。",
    "A teacher reads with pupils in a classroom. The scene reflects the preparation required before dependable cover reaches the lesson.": "講師が教室で生徒と一緒に本を読んでいます。確実な代講を授業に届けるために必要な事前準備を表す写真です。",
    "Before We Begin": "手配を始める前に",
    "Every assignment begins with a clear account of what the school requires.": "すべてのご依頼は、学校が必要としている内容を明確にすることから始まります。",
    "A school making contact is describing more than a date and a gap in the timetable. It is explaining a temporary difficulty within an established educational environment.": "学校からのお問い合わせは、日付と時間割の空きだけを伝えるものではありません。すでに運営されている教育環境の中で、どのような一時的な問題が起きているかを共有していただくものです。",
    "The age of the learners, the nature of the lessons, the journey to the school, the materials available, the duration of the assignment and the expectations placed upon the teacher all influence whether the arrangement can be undertaken properly.": "学習者の年齢、授業内容、学校までの移動、用意されている教材、ご依頼の期間、講師に求められる役割は、手配を適切に実施できるかどうかにすべて関係します。",
    "Our first task is to establish the facts: what is needed, what is known and what remains uncertain. We ask for the practical information required to assess the assignment clearly and identify any questions that must be resolved.": "最初に行うのは、何が必要で、何が分かっていて、何が未確認なのかを整理することです。ご依頼を正確に検討するための実務情報を伺い、確定前に解決すべき点を明らかにします。",
    "The process is deliberately straightforward. It is not intended to burden a school with administration. It exists so that the school, the teacher and Englishire share the same understanding before the first lesson begins.": "手順は意図的に分かりやすくしています。学校に余計な事務負担をかけるためではありません。最初の授業が始まる前に、学校、講師、Englishireが同じ内容を理解している状態をつくるためです。",
    "A clear beginning is the first protection against a confused arrival.": "最初に内容を明確にすることが、当日の混乱を防ぐ第一歩です。",
    "The Process at a Glance": "ご利用の流れの概要",
    "Seven stages, one clear line of responsibility.": "7つの段階を通じて、責任の所在を明確にします。",
    "Each stage settles a different question before the arrangement moves forward.": "手配を次へ進める前に、各段階で異なる確認事項を解決します。",
    "Listen": "内容を伺う",
    "Review": "全体を確認する",
    "Consider suitability": "適合性を判断する",
    "Confirm": "条件を確定する",
    "Prepare": "事前準備を行う",
    "Support": "授業を支援する",
    "Hand over": "引き継ぐ",
    "From Enquiry to Handover": "お問い合わせから引き継ぎまで",
    "What happens after a school makes contact.": "学校からお問い合わせをいただいた後の流れ。",
    "The sequence is practical, but the judgement within it matters.": "手順そのものは実務的ですが、各段階での判断が重要です。",
    "Listening": "内容を伺う",
    "The School Explains the Requirement": "学校から必要事項を共有",
    "The process begins with the circumstances as the school understands them. Cover may be required because of illness, leave, a recruitment gap, additional capacity or a programme of limited duration. The reason matters because it often determines the likely length, responsibilities and degree of continuity involved.": "手続きは、学校が把握している状況を伺うことから始まります。病気、休暇、採用までの空白、授業数の増加、期間限定のプログラムなど、代講が必要になる理由はさまざまです。その理由によって、想定期間、担当業務、必要な継続性が変わるため、背景の確認は重要です。",
    "We ask for the school location, requested dates, timetable, learner ages, approximate levels, class sizes, lesson format, available materials and any particular expectations. Where information is not yet known, the uncertainty should simply be stated.": "学校所在地、ご希望の日程、時間割、学習者の年齢、おおよそのレベル、クラス人数、授業形式、利用可能な教材、特に求めることを伺います。まだ分からない情報は、未確認であることをそのままお知らせください。",
    "There is no need for ceremony. A concise and candid account is of far greater value than a polished description which leaves the essential questions unanswered.": "形式ばった説明は必要ありません。重要な点が分からないままの整った文章より、簡潔で率直な説明の方が役立ちます。",
    "The school need not have solved the staffing difficulty before contacting us. It need only describe it as clearly as circumstances allow.": "お問い合わせの前に、学校側で人員問題を解決しておく必要はありません。現時点で分かる範囲を、できるだけ明確にお伝えください。",
    "Reviewing": "全体を確認する",
    "Englishire Reviews the Assignment as a Whole": "Englishireがご依頼全体を確認",
    "Once the details have been received, Englishire reviews the assignment as a whole. A timetable is not assessed in isolation from travel. A lesson format is not separated from the learners. A proposed duration is not separated from the continuity the school expects.": "情報を受け取った後、Englishireはご依頼を全体として確認します。時間割は移動条件と切り離さず、授業形式は学習者と切り離さず、予定期間は学校が求める継続性と切り離さずに検討します。",
    "We consider reporting time, stations and transfers, movement between classrooms, preparation periods, teaching materials, school routines, communication responsibilities and what the teacher may reasonably be expected to accomplish within the available time.": "到着時刻、利用駅と乗り換え、教室間の移動、準備時間、教材、学校の日常手順、連絡・報告の役割、限られた時間内に講師が現実的に行える内容を確認します。",
    "This stage often reveals the practical questions that require clarification. It is better for those questions to arise now than on the morning of the assignment.": "この段階で、実務上確認すべき点が見つかることがよくあります。担当当日の朝に判明するより、事前に確認できる方が安全です。",
    "An apparently minor detail may determine whether an arrangement is dependable in practice.": "一見小さな情報が、実際に確実な手配となるかどうかを左右することがあります。",
    "Considering Suitability": "適合性を判断する",
    "The Right Teacher Is Considered, Not Merely a Free One": "予定が空いているだけでなく、適切な講師を検討",
    "Availability is necessary, but it is not the standard by which a teacher should be selected. The relevant question is whether an available teacher is also appropriate for the learners, lesson format, school environment and responsibilities of the assignment.": "予定が空いていることは必要ですが、それだけで講師を選ぶことはできません。対応可能な講師が、学習者、授業形式、学校環境、担当業務にも適しているかを判断します。",
    "A teacher suited to adult conversation may not be the natural choice for a lively class of very young children. A confident generalist may not be appropriate for a specialist examination programme. A teacher whose journey is technically possible may still be unable to reach the school with sufficient reliability.": "成人英会話に適した講師が、幼い子どもの活発なクラスにも適しているとは限りません。幅広く教えられる講師でも、専門的な試験対策には合わない場合があります。経路上は移動可能でも、時間どおりの到着を十分に見込めないこともあります。",
    "Suitability therefore involves professional judgement rather than a simple diary search.": "そのため、適合性の判断は、単に予定表の空きを探す作業ではなく、専門的な検討を必要とします。",
    "A vacant timetable is not, by itself, a qualification.": "予定が空いていること自体は、適任であることの証明にはなりません。",
    "Confirming": "条件を確定する",
    "The Arrangement Is Set Out Clearly": "手配内容を明確に確定",
    "Where a suitable teacher is available and the assignment can be undertaken properly, the arrangement is confirmed. The dates, reporting time, location, lesson schedule, principal responsibilities and agreed practical terms should be clear to everyone concerned.": "適切な講師が対応可能で、ご依頼を責任を持って実施できる場合に手配を確定します。日程、到着時刻、所在地、授業時間、主な担当業務、合意した実務条件を関係者全員に明確にします。",
    "An enquiry, discussion or expression of availability is not a confirmation. The school should know precisely when the arrangement has become definite, and any material change afterwards should be discussed rather than assumed.": "お問い合わせ、確認のやり取り、空き状況の提示だけでは、手配の確定にはなりません。学校には、いつ正式に確定したかを明確にお伝えします。確定後に重要な変更がある場合も、当然に受け入れられたものとせず、改めて相談します。",
    "This protects the school from uncertainty and the teacher from arriving to an assignment different from the one accepted.": "これにより、学校側の不確実性を減らし、講師が引き受けた内容と異なる現場に到着することを防ぎます。",
    "Clarity at confirmation prevents avoidable negotiation at the school gate.": "確定時に条件を明確にすることで、到着後に避けられたはずの調整が生じるのを防ぎます。",
    "Preparing": "事前準備を行う",
    "The Teacher Receives a Useful Briefing": "講師に実用的な事前説明を共有",
    "Confirmation establishes the assignment. Preparation equips the teacher to carry it out. Before arrival, the teacher should receive the timetable, reporting instructions, school contact, lesson information, learner details, materials, classroom expectations and any procedures that bear upon the work.": "確定によって担当内容が決まり、準備によって講師が実施できる状態になります。到着前に、時間割、受付・到着方法、学校側の連絡先、授業情報、学習者情報、教材、授業上の期待、担当に関係する手順を共有します。",
    "Not every school requires a lengthy briefing document. What matters is that the essential information reaches the teacher in a form that can be understood and used.": "すべての学校に長い説明資料が必要なわけではありません。重要なのは、必要な情報が、講師が理解し実際に使える形で届くことです。",
    "Where cover extends beyond a single day, the briefing may also need to address homework, learner progress, reporting, communication with colleagues and continuity between lessons.": "代講が1日を超える場合は、宿題、学習者の進捗、報告、同僚との連絡、授業間の継続についても説明が必要になることがあります。",
    "Professional teacher cover begins before the classroom door opens.": "専門的な代講は、教室の扉が開く前から始まっています。",
    "Supporting": "授業を支援する",
    "The Assignment Is Conducted With Calm Communication": "落ち着いた連絡のもとで担当を実施",
    "On the agreed day, the teacher reports according to the confirmed arrangements, allows appropriate time for introductions and prepares for the first lesson. The aim is not to announce the temporary nature of the arrangement, but to help the school day proceed with as little disturbance as possible.": "合意した当日、講師は確定した内容に従って到着し、挨拶と確認の時間を取り、最初の授業を準備します。短期担当であることを強調するのではなく、学校の一日をできるだけ混乱なく進めることが目的です。",
    "During longer assignments, circumstances may change. Materials may be revised, classes may move, an absence may be extended or the school may identify further responsibilities. Such changes should be communicated promptly and considered properly.": "期間の長いご依頼では、状況が変わることがあります。教材の変更、教室の移動、欠勤期間の延長、追加業務の発生などは、速やかに共有し、改めて適切に検討します。",
    "Flexibility is valuable. Vagueness is not. The distinction is maintained through timely, proportionate communication.": "柔軟な対応は大切ですが、曖昧なまま進めることとは異なります。必要な内容を、適切なタイミングと分量で連絡することで区別します。",
    "The best temporary cover is often the cover that permits the school to concentrate upon everything else.": "優れた短期の代講とは、学校が他の重要な業務に集中できる状態をつくるものです。",
    "Handing Over": "引き継ぐ",
    "The Assignment Concludes Without Losing What Was Learned": "授業で得た情報を失わずに担当を終える",
    "A single-day assignment may require little more than a clear note concerning work completed and any matter the returning teacher should know. A longer placement may call for a more substantial handover of learner progress, materials, homework, changes to the timetable and outstanding responsibilities.": "1日だけの担当であれば、実施した内容と復帰する講師が知るべき事項を簡潔に記録するだけで足りることがあります。長期の担当では、学習者の進捗、教材、宿題、時間割の変更、未完了の業務について、より詳しい引き継ぎが必要になります。",
    "Where further cover is required, the next stage is discussed rather than presumed. Dates, responsibilities and availability may have changed, and each continuation deserves the same clarity as the original arrangement.": "追加の代講が必要な場合は、自動的に継続するのではなく、次の手配を相談します。日程、担当業務、空き状況が変わっている可能性があるため、継続時にも最初と同じ明確さが必要です。",
    "A proper conclusion protects continuity beyond the temporary teacher's final lesson.": "適切な終了と引き継ぎが、短期講師の最後の授業後も学習の継続を守ります。",
    "Temporary work should end cleanly, not simply cease.": "短期の担当は、ただ途切れるのではなく、明確に引き継いで終えるべきです。",
    "What Helps at the Outset": "最初に共有いただきたい情報",
    "Useful information allows a useful answer.": "必要な情報があれば、より正確に回答できます。",
    "Urgent circumstances do not always permit every detail to be assembled before contact is made. Schools are welcome to send what is known and identify what remains uncertain.": "急ぎの場合、連絡前にすべての情報をそろえられないこともあります。分かっている内容を送り、未確認の点を明記してください。",
    "Nevertheless, the following information allows the assignment to be considered with fewer assumptions and often with greater efficiency.": "次の情報があると、推測を減らし、より効率的にご依頼を検討できます。",
    "School and contact details": "学校・担当者情報",
    "The school name, address, nearest station and the person responsible for the enquiry.": "学校名、住所、最寄り駅、お問い合わせ担当者。",
    "Dates and timetable": "日程・時間割",
    "Requested dates, reporting time, lesson periods, breaks, finish time and movement between locations.": "ご希望の日程、到着時刻、授業時間、休憩、終了時刻、校舎や教室間の移動。",
    "Learners and classes": "学習者・クラス",
    "Ages, approximate levels, class sizes and any needs or circumstances relevant to the teacher.": "年齢、おおよそのレベル、クラス人数、講師が知るべき配慮事項や状況。",
    "Lessons and materials": "授業・教材",
    "Objectives, teaching format, materials, work already completed, homework and reporting expectations.": "授業目標、指導形式、教材、すでに終えた内容、宿題、報告の方法。",
    "School procedures": "学校の手順",
    "Arrival, dress, conduct, safeguarding, classroom routines and communication arrangements.": "到着・受付、服装、振る舞い、安全管理、授業中の手順、連絡方法。",
    "The likely duration": "想定期間",
    "Whether the requirement is isolated, recurring, open-ended or expected to conclude on a particular date.": "単発、定期、終了日未定、または特定の日に終了予定のいずれか。",
    "When the Answer May Be No": "お断りする場合",
    "Occasionally, declining is the more responsible decision.": "責任ある判断として、ご依頼をお断りする場合があります。",
    "Not every enquiry can or should become an assignment. A school is better served by a prompt and honest answer than by a convenient promise followed by uncertainty.": "すべてのお問い合わせを手配に進められるわけではなく、進めるべきでもありません。後から不確実になる都合のよい約束より、早い段階で正直に回答する方が学校のためになります。",
    "A decision to decline does not suggest that the requirement lacks importance. It means only that we are not satisfied the work can be undertaken to an appropriate standard under the circumstances presented.": "お断りすることは、ご依頼が重要ではないという意味ではありません。提示された状況では、適切な水準で実施できると判断できないという意味です。",
    "The essential requirements remain unclear": "重要な必要事項が不明な場合",
    "The assignment cannot be judged properly without sufficient information concerning the timetable, learners or responsibilities.": "時間割、学習者、担当業務について十分な情報がなければ、責任ある判断はできません。",
    "No suitably matched teacher is available": "適合する講師を確保できない場合",
    "A free teacher is not necessarily an appropriate teacher.": "予定が空いている講師が、必ずしもご依頼に適しているとは限りません。",
    "The journey makes punctual attendance uncertain": "時間どおりの到着を確実に見込めない場合",
    "An arrangement should remain dependable in ordinary Tokyo travel conditions.": "東京の通常の交通状況で、時間どおりの到着を現実的に見込める必要があります。",
    "The expectations fall outside appropriate expertise": "必要な専門性の範囲を超える場合",
    "Specialist work deserves a teacher with the relevant capability rather than an improvised substitute.": "専門性の高い授業には、その場しのぎの代講ではなく、必要な能力を持つ講師が必要です。",
    "The terms change the nature of the assignment": "条件変更によってご依頼の性質が変わる場合",
    "A material change may require the arrangement to be reconsidered rather than treated as automatically accepted.": "重要な変更がある場合は、自動的に受け入れたものとせず、手配を改めて検討します。",
    "What the Process Protects": "この手順が守るもの",
    "Clarity for the school, preparedness for the teacher and continuity for the learner.": "学校には明確な条件を、講師には十分な準備を、学習者には授業の継続を。",
    "The School": "学校",
    "The school should understand what has been agreed, who is arriving, what information remains required and how changes will be handled.": "学校は、合意した内容、到着する講師、追加で必要な情報、変更が生じた場合の対応を把握できる状態にします。",
    "The Teacher": "講師",
    "The teacher should receive sufficient information to arrive punctually, understand the environment and carry out the work with professional confidence.": "講師には、時間どおりに到着し、環境を理解し、専門的な自信を持って担当するために十分な情報を共有します。",
    "The Learner": "学習者",
    "The learner should experience a purposeful lesson and the greatest degree of continuity that temporary circumstances reasonably permit.": "学習者には、目的のある授業と、短期の状況で可能な限り高い継続性を提供します。",
    "Every stage returns to the same standard: suitability before convenience, preparation before placement and communication before assumption.": "すべての段階で同じ基準に戻ります。利便性より適合性、配置より先に準備、思い込みより先に連絡と確認を重視します。",
    "The process described on this page is the practical expression of principles set out in": "このページの手順は、次の文書に示す原則を実務に落とし込んだものです。",
    ". That document explains the wider responsibilities which inform how assignments are considered, teachers are prepared and school relationships are conducted.": "この文書では、ご依頼の検討、講師の準備、学校との関係に関わる、より広い責任について説明しています。",
    "Practical Questions": "ご利用の流れに関する質問",
    "Matters schools quite reasonably ask.": "学校からよく寄せられる実務上の質問。",
    "These answers concern the process itself. The fuller questions page addresses the wider service in greater detail.": "ここでは手順そのものに関する質問にお答えします。サービス全体については、よくあるご質問のページで詳しく説明しています。",
    "How quickly will the school receive an answer?": "どのくらいで回答を受け取れますか？",
    "This depends upon the urgency, clarity and complexity of the enquiry. We respond as promptly as circumstances permit, but the assignment is not confirmed until Englishire has expressly confirmed it.": "お問い合わせの緊急度、情報の明確さ、内容の複雑さによって異なります。状況が許す限り速やかに回答しますが、Englishireから明確な確定連絡があるまでは手配済みではありません。",
    "May we make contact before cover is required?": "代講が必要になる前に連絡してもよいですか？",
    "Certainly. An advance introduction can be useful, particularly where a school has recurring requirements or a timetable that would benefit from prior understanding.": "はい。定期的に代講が必要になる可能性がある学校や、事前に時間割を理解しておくと有効な学校では、早めのご連絡が役立ちます。",
    "What happens if some details are not yet known?": "まだ分からない情報がある場合はどうなりますか？",
    "Send what is available and state what remains uncertain. We can then explain which details are essential before the arrangement can be reviewed or confirmed.": "現時点で分かる情報を送り、未確認の点を明記してください。検討または確定の前に、どの情報が不可欠かをEnglishireからお伝えします。",
    "Does making an enquiry guarantee cover?": "問い合わせれば、必ず代講を手配できますか？",
    "No. Cover depends upon the requirements, teacher suitability and availability. We do not promise an arrangement before we are satisfied it can be undertaken properly.": "いいえ。対応可否は、ご依頼内容、講師の適合性、空き状況によって決まります。適切に実施できると判断する前に手配を約束することはありません。",
    "Can the arrangement change after confirmation?": "確定後に手配内容を変更できますか？",
    "Changes may be possible, though they should be discussed. A revised timetable, location, learner group or duration may affect suitability and availability.": "変更できる場合がありますが、事前の相談が必要です。時間割、所在地、学習者のグループ、期間の変更は、講師の適合性や空き状況に影響することがあります。",
    "What should the teacher receive before arrival?": "講師には到着前に何を共有しますか？",
    "At minimum, the confirmed timetable, location, reporting instructions, contact details, lesson information and any important school procedures or expectations.": "少なくとも、確定した時間割、所在地、到着・受付方法、連絡先、授業情報、重要な学校手順と期待事項を共有します。",
    "A prior introduction makes a later conversation rather less hurried.": "事前に学校について共有していただくと、実際のご依頼をより落ち着いて進められます。",
    "Schools need not wait for an absence before introducing themselves. A short account of the school, its timetable and the sort of cover that may one day arise can provide useful context when circumstances eventually require a prompt answer.": "講師が欠勤するまで待たずに、学校についてご連絡いただけます。学校の概要、時間割、将来想定される代講を事前に共有していただくと、急ぎの回答が必要になったときの重要な背景情報になります。",
    "Tell us about your school and the circumstances in which temporary English teacher cover might prove useful.": "学校の概要と、英語講師の短期代講が必要になり得る状況をお知らせください。",
    "Tell us what the school requires. We will review the assignment and explain clearly what can be provided.": "学校が必要としている内容をお知らせください。ご依頼を確認し、対応できる内容を明確にご説明します。",
    "Please include the school location, requested dates, lesson times, learner age groups and the nature of the assignment.": "学校所在地、ご希望の日程、授業時間、学習者の年齢層、ご依頼内容をお知らせください。",
    "Read about teacher cover": "講師の代講・短期手配について見る",
    "How it works page actions": "ご利用の流れページの操作",
    "Englishire process summary": "Englishireの手順概要",
    "A teacher reading to pupils in a historic wooden classroom": "歴史ある木造教室で生徒に本を読み聞かせる講師",
    "Englishire process overview": "Englishireのご利用の流れ",
    "A clear account of how Englishire considers, confirms, prepares and reviews temporary English teacher cover for schools throughout Tokyo.": "東京都内の学校向け英語講師の代講・短期手配を、Englishireがどのように検討、確定、準備、確認するかを明確に説明します。",
    "How Temporary Teacher Cover Works | Englishire Tokyo": "英語講師の代講・短期手配の流れ | Englishire Tokyo",
    "From first enquiry to final handover, discover Englishire's considered process for temporary English teacher cover in Tokyo.": "最初のお問い合わせから最終の引き継ぎまで、東京の学校向け英語講師代講を丁寧に進めるEnglishireの手順をご案内します。",
    "Englishire temporary English teacher cover process for Tokyo schools": "東京の学校向けEnglishire英語講師代講のご利用の流れ",
}
