"""Exact Japanese translations for the second half of the Privacy Policy."""

TRANSLATIONS = {
    "How long it may be kept": "保管期間",
    "Information is retained only for as long as reasonably required for the purpose for which it was obtained, for a related professional relationship, or to satisfy legal, accounting, tax, security or record-keeping obligations.": "情報は、取得した目的、関係する業務上の関係、または法令、会計、税務、安全管理、記録保存上の義務に合理的に必要な期間だけ保管します。",
    "Different information may be kept for different periods. An unsuccessful preliminary enquiry, for example, need not be treated in precisely the same manner as records relating to a completed assignment or payment.": "情報の種類によって保管期間が異なる場合があります。たとえば、成立しなかった初期のお問い合わせと、完了したご依頼や支払いに関する記録を、まったく同じ方法で扱う必要はありません。",
    "Information which is no longer reasonably required should be deleted, anonymised or otherwise dealt with appropriately, subject to lawful retention requirements and practical backup arrangements.": "合理的に不要となった情報は、法令上の保存要件と実務上のバックアップ事情に従い、削除、匿名化、その他の適切な方法で処理します。",
    "Security": "安全管理",
    "Englishire endeavours to use reasonable organisational and technical measures to protect personal information against unauthorised access, loss, misuse, alteration or disclosure.": "Englishireは、個人情報を不正アクセス、紛失、不正利用、改変、漏えいから守るため、合理的な組織上・技術上の対策を講じるよう努めます。",
    "Such measures may include restricted access, sensible account and password practices, secure service providers, software updates, record controls and care when transmitting assignment information.": "対策には、アクセス制限、適切なアカウント・パスワード管理、安全性を考慮したサービス提供者の利用、ソフトウェア更新、記録管理、ご依頼情報を送信する際の注意などが含まれる場合があります。",
    "No website, email system or storage method can be guaranteed to be entirely secure. Schools should therefore avoid including unnecessary sensitive information in ordinary email or web-form correspondence.": "ウェブサイト、メール、保存方法の安全性を完全に保証することはできません。そのため、通常のメールやウェブフォームには、不要な機微情報を含めないでください。",
    "Cookies and technical information": "Cookieと技術情報",
    "At the review date shown above, the website code does not set cookies or use browser storage. It does not include analytics, advertising trackers or embedded third-party media.": "上記の確認日時点で、このサイトのコードはCookieを設定せず、ブラウザ保存機能も使用していません。アクセス解析、広告トラッカー、第三者メディアの埋め込みも含まれていません。",
    "If analytics, embedded media, advertising or other non-essential technologies are introduced, the": "アクセス解析、埋め込みメディア、広告、その他の必須でない技術を導入する場合は、",
    "Cookie Policy": "Cookieポリシー",
    "should explain them and, where required, an appropriate choice or consent mechanism should be provided.": "で内容を説明し、必要な場合は適切な選択または同意の仕組みを提供します。",
    "Browser settings may permit you to refuse or delete cookies, though doing so may affect certain website functions.": "ブラウザ設定でCookieを拒否または削除できる場合がありますが、一部のサイト機能に影響することがあります。",
    "Services outside Japan": "日本国外のサービス",
    "Some website, email, storage, administration or other service providers may process or store information outside Japan.": "ウェブサイト、メール、保存、事務、その他のサービス提供者が、日本国外で情報を処理または保管する場合があります。",
    "Where that occurs, Englishire shall endeavour to consider the nature of the provider, the information involved and any safeguards or legal requirements applicable to the transfer or processing.": "その場合、Englishireは、サービス提供者の性質、対象となる情報、移転または処理に適用される安全措置や法的要件を考慮するよう努めます。",
    "The location of a service provider may change over time, and the provider's own privacy terms may also apply to its handling of information.": "サービス提供者の所在地は変更される場合があり、情報の取扱いにはその提供者自身のプライバシー条件も適用されることがあります。",
    "Information concerning children": "子どもに関する情報",
    "Englishire's website and enquiry form are intended principally for schools, education providers and adult representatives.": "Englishireのウェブサイトとお問い合わせフォームは、主に学校、教育機関、成人の担当者を対象としています。",
    "A school should not provide identifying or sensitive information about a child unless it has a proper reason and lawful authority to do so.": "正当な理由と法的権限がある場合を除き、子どもを特定できる情報や機微情報を学校から提供しないでください。",
    "Where a temporary teacher genuinely needs to know something relevant to a learner's safety, accessibility or classroom support, the school should share only what is appropriate and necessary for the assignment.": "短期講師が学習者の安全、アクセシビリティ、授業上の支援に関する情報を本当に知る必要がある場合は、ご依頼に適切かつ必要な範囲だけを共有してください。",
    "Your choices and requests": "ご本人の選択と請求",
    "Subject to applicable law and reasonable verification, an individual may contact Englishire to ask about personal information concerning them, or to request correction, deletion, restriction, cessation of use or another appropriate form of handling.": "適用法令と合理的な本人確認の範囲で、ご本人はEnglishireに連絡し、自身に関する個人情報の照会、訂正、削除、取扱いの制限、利用停止、その他の適切な対応を求めることができます。",
    "Some requests may be limited where information must be retained for legal, accounting, contractual, security or other legitimate reasons.": "法令、会計、契約、安全管理、その他の正当な理由で情報を保管する必要がある場合、ご請求に対応できる範囲が限られることがあります。",
    "We may ask for information sufficient to confirm the identity and authority of the person making the request before disclosing or changing personal information.": "個人情報を開示または変更する前に、ご請求者の本人性と権限を確認するために必要な情報を求める場合があります。",
    "Changes to this policy": "本ポリシーの変更",
    "This policy may be revised when the website, service, technology or legal requirements change.": "ウェブサイト、サービス、技術、法的要件が変わった場合、本ポリシーを改定することがあります。",
    "The date at the top of the page indicates when the policy was last reviewed. Material changes should be presented clearly rather than concealed within minor wording.": "ページ上部の日付は、最後に内容を確認した日を示します。重要な変更は、小さな文言変更の中に隠さず明確に示します。",
    "Questions, requests or concerns concerning privacy may be sent through the Englishire": "プライバシーに関する質問、請求、懸念事項は、Englishireの",
    "contact page": "お問い合わせページ",
    "Please provide sufficient information for the matter to be identified and considered. Please do not include further sensitive information unless it is genuinely required.": "内容を特定して確認できるだけの情報をお知らせください。本当に必要な場合を除き、追加の機微情報は含めないでください。",
    "PRIVACY": "PRIVACY",
    "Clear purpose. Sensible restraint.": "目的を明確にし、必要な範囲にとどめます。",
    "A Final Reassurance": "最後に",
    "Courtesy does not end when information is submitted.": "情報を受け取った後も、丁寧な取扱いを続けます。",
    "Englishire believes that trust is earned through the ordinary habits of careful handling: asking for information with a reason, using it for that reason, sharing it only where justified and retaining it no longer than necessary.": "Englishireは、情報を求める理由を明確にし、その理由のために利用し、正当な場合だけ共有し、必要以上に保管しないという、日常的で慎重な取扱いによって信頼が築かれると考えています。",
    "Should you have a question concerning privacy, we should be pleased to consider it directly.": "プライバシーについてご質問がある場合は、個別に確認します。",
    "Contact Englishire": "Englishireへ問い合わせる",
    "Questions concerning personal information may be sent through the contact page.": "個人情報に関するご質問は、お問い合わせページからお送りください。",
    "This website works best with JavaScript enabled, though the complete Privacy Policy and every essential link remain available without it.": "このサイトはJavaScriptを有効にすると快適にご利用いただけますが、プライバシーポリシー全文と主要なリンクはJavaScriptなしでも確認できます。",
    "A carefully arranged notebook and correspondence on a quiet desk": "静かな机の上に整えられたノートと書類",
    "Privacy Policy sections": "プライバシーポリシーの項目",
    "Englishire's Privacy Policy explains what personal information may be received, why it is used, how it is protected and the choices available to individuals.": "Englishireのプライバシーポリシーは、受け取る可能性のある個人情報、利用目的、保護方法、ご本人が行える選択を説明します。",
    "A clear explanation of how Englishire handles personal information.": "Englishireによる個人情報の取扱いを分かりやすく説明します。",
    "How Englishire receives, uses, protects and retains personal information.": "Englishireが個人情報を受け取り、利用し、保護し、保管する方法を説明します。",
}
