"""Exact Japanese translations for the first half of the Privacy Policy."""

TRANSLATIONS = {
    "Your information deserves the same careful consideration as your enquiry.": "お預かりする情報も、お問い合わせと同じように慎重に扱います。",
    "This page explains what information Englishire may receive, why it may be needed and how it is handled.": "このページでは、Englishireが受け取る可能性のある情報、必要となる理由、取扱方法を説明します。",
    "Privacy should be explained plainly rather than concealed behind unnecessarily complicated language. We therefore set out below the purposes for which information may be used, the circumstances in which it may be shared and the choices available to you.": "プライバシーについては、不必要に複雑な表現で隠さず、分かりやすく説明するべきだと考えています。以下に、情報を利用する目的、共有する場合、利用者が行える選択を示します。",
    "20 July 2026": "2026年7月20日",
    "Trust is earned not merely through promises, but through the manner in which information is handled.": "信頼は約束だけでなく、情報をどのように扱うかによって築かれます。",
    "The Principle": "基本原則",
    "Information should be requested for a reason.": "情報を求めるときは、明確な理由が必要です。",
    "Englishire receives information principally when a school makes an enquiry, introduces itself, requests temporary teacher cover or otherwise communicates with us.": "Englishireは主に、学校からのお問い合わせ、学校の事前紹介、講師代講のご相談、その他の連絡を受けたときに情報を受け取ります。",
    "We endeavour to request only what is reasonably required to understand the matter, respond properly and manage any resulting professional relationship.": "ご相談内容を理解し、適切に回答し、その後の業務関係を管理するために合理的に必要な情報だけを求めるよう努めます。",
    "Information is not collected merely because a form makes it possible to ask for it.": "フォーム上で質問できるという理由だけで、情報を収集することはありません。",
    "Clear purpose should come before collection.": "収集する前に、目的を明確にします。",
    "The chapters": "項目一覧",
    "1. Information we may receive": "1. 受け取る可能性のある情報",
    "2. Why we use it": "2. 利用目的",
    "3. The basis for handling it": "3. 取扱いの根拠",
    "4. When information may be shared": "4. 情報を共有する場合",
    "5. How long it may be kept": "5. 保管期間",
    "6. Security": "6. 安全管理",
    "7. Cookies and technical information": "7. Cookieと技術情報",
    "8. Services outside Japan": "8. 日本国外のサービス",
    "9. Information concerning children": "9. 子どもに関する情報",
    "10. Your choices and requests": "10. ご本人の選択と請求",
    "11. Changes to this policy": "11. 本ポリシーの変更",
    "12. Contact": "12. お問い合わせ",
    "Information we may receive": "受け取る可能性のある情報",
    "Depending upon the nature of your enquiry or relationship with Englishire, we may receive information such as:": "お問い合わせ内容やEnglishireとの関係に応じて、次のような情報を受け取る場合があります。",
    "your name, position, organisation, email address and telephone number;": "氏名、役職、所属組織、メールアドレス、電話番号",
    "the name, address, website, nearest station and other practical details concerning a school or education provider;": "学校または教育機関の名称、住所、ウェブサイト、最寄り駅、その他の実務情報",
    "dates, timetables, learner age groups, class sizes, lesson formats and assignment requirements;": "日程、時間割、学習者の年齢層、クラス人数、授業形式、ご依頼内容",
    "information contained in correspondence, forms, documents or other materials you choose to send;": "利用者が送付するメール、フォーム、文書、その他の資料に含まれる情報",
    "administrative information required for quotations, agreements, invoicing, payment or record-keeping;": "見積り、合意、請求、支払い、記録管理に必要な事務情報",
    "technical information associated with use of the website, such as browser type, device information, IP address and basic access records, where such information is produced by the website or it's service providers.": "ウェブサイトまたはそのサービス提供者が生成する場合の、ブラウザの種類、端末情報、IPアドレス、基本的なアクセス記録など、サイト利用に関する技術情報",
    "Schools should avoid sending sensitive information about a learner, parent, teacher or other individual unless it is genuinely necessary, appropriate and lawful to do so.": "本当に必要で、適切かつ法令上認められる場合を除き、学習者、保護者、講師、その他の個人に関する機微な情報を送らないでください。",
    "The enquiry form transmits the information you enter securely to Formspree, a form-processing service provider, so that the enquiry can be delivered to Englishire. Formspree may process and retain the submission in accordance with its own privacy terms and the settings applied to Englishire’s form account.": "お問い合わせフォームに入力した情報は、フォーム処理サービスのFormspreeへ安全に送信され、Englishireへ届けられます。Formspreeは、同社のプライバシー条件およびEnglishireのフォームアカウント設定に従って、送信内容を処理・保管する場合があります。",
    "Why we use it": "利用目的",
    "Personal information may be used for purposes including:": "個人情報は、次の目的で利用する場合があります。",
    "receiving and responding to enquiries;": "お問い合わせの受領と回答",
    "understanding a school, assignment, timetable or teaching requirement;": "学校、ご依頼、時間割、授業上の必要事項の把握",
    "considering teacher suitability and availability;": "講師の適合性と空き状況の検討",
    "communicating about an enquiry, proposed assignment or confirmed arrangement;": "お問い合わせ、提案中のご依頼、確定した手配に関する連絡",
    "preparing, administering and reviewing temporary teacher cover;": "講師の代講・短期手配の準備、運営、確認",
    "producing quotations, agreements, invoices and related records;": "見積書、合意書、請求書、関連記録の作成",
    "maintaining reasonable records of previous communications and assignments;": "過去の連絡とご依頼に関する合理的な記録の保管",
    "protecting the website, Englishire, schools, teachers and other individuals from misuse, fraud, security concerns or unlawful activity;": "不正利用、詐欺、セキュリティ上の問題、違法行為から、サイト、Englishire、学校、講師、その他の個人を守ること",
    "complying with legal, regulatory, accounting or tax obligations;": "法令、規制、会計、税務上の義務への対応",
    "improving the clarity, usefulness and operation of the website and service.": "ウェブサイトとサービスの分かりやすさ、有用性、運営の改善",
    "We do not intend to use personal information in a manner which is materially incompatible with the purpose for which it was obtained without first providing an appropriate explanation or obtaining consent where required.": "適切な説明を行う、または必要な同意を得ることなく、取得目的と実質的に両立しない方法で個人情報を利用することは意図していません。",
    "The basis for handling it": "取扱いの根拠",
    "Englishire handles personal information where doing so is reasonably connected with an enquiry, requested service, proposed or existing arrangement, legal obligation, legitimate operational need or consent provided by the individual.": "Englishireは、お問い合わせ、依頼されたサービス、提案中または既存の手配、法的義務、正当な業務上の必要性、または本人の同意と合理的な関係がある場合に個人情報を取り扱います。",
    "Where Japanese law requires a particular notice, consent, procedure or form of handling, Englishire shall endeavour to follow the applicable requirement.": "日本法により特定の通知、同意、手続き、取扱方法が求められる場合、Englishireは適用される要件に従うよう努めます。",
    "The submission of an enquiry does not require you to provide information which is unrelated to the matter being considered.": "お問い合わせ内容と関係のない情報を提供する必要はありません。",
    "When information may be shared": "情報を共有する場合",
    "Englishire does not sell personal information.": "Englishireは個人情報を販売しません。",
    "Information may, however, be shared where reasonably necessary with:": "ただし、合理的に必要な場合、次の相手と情報を共有することがあります。",
    "teachers or prospective teachers who require relevant assignment information;": "関係するご依頼情報を必要とする講師または候補講師",
    "schools, education providers or authorised representatives involved in an enquiry or assignment;": "お問い合わせまたはご依頼に関係する学校、教育機関、正当な権限を持つ担当者",
    "service providers supporting website hosting, forms, email, storage, administration, accounting, security or other business functions;": "ウェブサイトのホスティング、フォーム、メール、保存、事務、会計、セキュリティ、その他の業務を支援するサービス提供者",
    "professional advisers, insurers, accountants or legal advisers where their assistance is reasonably required;": "支援が合理的に必要な専門顧問、保険会社、会計士、法律顧問",
    "public authorities, regulators, courts or other parties where disclosure is required or permitted by law;": "法令により開示が必要または認められる場合の公的機関、規制当局、裁判所、その他の関係者",
    "another organisation involved in a legitimate restructuring, transfer or succession of the business, subject to appropriate handling of the information.": "情報を適切に取り扱うことを条件として、正当な事業再編、譲渡、承継に関係する他の組織",
    "Where information is shared for an assignment, we endeavour to limit it to what the recipient reasonably needs to know.": "ご依頼のために情報を共有する場合、受取人が合理的に知る必要のある範囲に限定するよう努めます。",
}
