"""Exact Japanese translations for the second half of the Questions page."""

TRANSLATIONS = {
    "Chapter VII": "第VII章",
    "What happens after the school sends its requirement.": "学校から必要事項を送った後の流れ。",
    "How does a school begin an enquiry?": "学校はどのように問い合わせを始めますか？",
    "The school may use the": "学校は",
    "enquiry page": "お問い合わせページ",
    "and provide the practical information available at the time.": "から、その時点で分かる実務情報を送ることができます。",
    "What happens after the enquiry is sent?": "問い合わせを送った後はどうなりますか？",
    "Englishire reviews the school, timetable, journey, learners, lesson expectations, duration and teacher suitability. Further questions may be asked before any answer is given.": "Englishireが、学校、時間割、移動条件、学習者、授業内容、期間、講師の適合性を確認します。回答前に追加の質問をする場合があります。",
    "Does sending an enquiry email reserve a teacher?": "問い合わせメールを送ると講師を確保できますか？",
    "No. Sending an enquiry begins the review process. No teacher is reserved or confirmed merely because an email has been sent.": "いいえ。お問い合わせを送ると検討が始まりますが、メールを送っただけで講師が確保・確定されることはありません。",
    "How is confirmation provided?": "手配の確定はどのように連絡されますか？",
    "Confirmation should identify the agreed dates, timetable, location, principal responsibilities and any relevant practical terms. Until confirmation is expressly given, the enquiry remains under consideration.": "確定連絡では、合意した日程、時間割、所在地、主な担当業務、関係する実務条件を明確にします。明確な確定連絡があるまでは、引き続き検討中です。",
    "Why might further questions be necessary?": "なぜ追加の質問が必要になることがありますか？",
    "A missing detail may affect punctuality, lesson preparation, learner suitability or the responsibilities expected of the teacher. Clarification before confirmation is preferable to negotiation at the school gate.": "不足している情報が、時間どおりの到着、授業準備、学習者への適合性、講師に求める業務に影響することがあります。到着後に調整するより、確定前に確認する方が適切です。",
    "Chapter VIII": "第VIII章",
    "Travel, arrival and the arrangements surrounding the first lesson.": "移動、到着、最初の授業までの手配。",
    "Why is the nearest station important?": "なぜ最寄り駅が重要ですか？",
    "Tokyo journeys depend upon more than the address. Railway lines, transfers, walking time and reporting arrangements all affect whether the teacher can arrive punctually.": "東京での移動は住所だけでは判断できません。路線、乗り換え、徒歩時間、到着・受付方法が、講師が時間どおりに到着できるかに影響します。",
    "How early should the teacher arrive?": "講師は何分前に到着しますか？",
    "The reporting time should be agreed in advance and allow for sign-in, introductions, locating rooms, collecting materials and receiving any final briefing.": "到着時刻は事前に合意し、受付、挨拶、教室の確認、教材の受け取り、最終説明に必要な時間を確保します。",
    "Should the school explain the dress code?": "学校から服装規定を伝える必要がありますか？",
    "Yes. Even where the expectation appears obvious to the school, a brief statement prevents unnecessary uncertainty.": "はい。学校側には当然に思える内容でも、短く明示することで不要な不確実性を防げます。",
    "What access information should be supplied?": "どのような入館情報を共有すればよいですか？",
    "The entrance, floor, reception or security procedure, contact person and any difficulty locating the building should be mentioned.": "入口、階、受付・警備手順、担当者、建物を見つけにくい場合の案内をお知らせください。",
    "Should safeguarding or emergency procedures be explained?": "安全管理や緊急時の手順も説明する必要がありますか？",
    "Yes. The teacher should receive the procedures relevant to the assignment and know whom to contact if a concern arises.": "はい。担当に関係する手順と、問題が生じた場合の連絡先を講師に共有してください。",
    "Chapter IX": "第IX章",
    "Fees, changes, records and matters which should be agreed rather than assumed.": "料金、変更、記録など、推測せず合意しておくべき事項。",
    "How are fees determined?": "料金はどのように決まりますか？",
    "Fees depend upon the assignment, duration, timetable, location, preparation required and other practical considerations. The applicable arrangement should be agreed before confirmation.": "料金は、ご依頼内容、期間、時間割、所在地、必要な準備、その他の実務条件によって決まります。適用する条件は、手配の確定前に合意します。",
    "How is transport treated?": "交通費はどのように扱いますか？",
    "The treatment of transport should be made clear as part of the agreed arrangement. Precise location information is necessary so that travel can be considered realistically.": "交通費の扱いは、合意する条件の一部として明確にします。移動を現実的に検討するため、正確な所在地情報が必要です。",
    "What if the timetable changes after confirmation?": "確定後に時間割が変わった場合はどうなりますか？",
    "Englishire should be informed promptly. A material change to dates, times, location, learner groups or responsibilities may affect suitability, availability or the agreed terms.": "速やかにEnglishireへお知らせください。日程、時間、所在地、学習者のグループ、担当業務の重要な変更は、適合性、空き状況、合意条件に影響する場合があります。",
    "May a school cancel or shorten an assignment?": "学校はご依頼をキャンセルまたは短縮できますか？",
    "Any cancellation or reduction should be discussed promptly and handled according to the terms agreed for that assignment.": "キャンセルや短縮は速やかに相談し、そのご依頼で合意した条件に従って扱います。",
    "How is personal information handled?": "個人情報はどのように扱いますか？",
    "Personal information is handled according to the": "個人情報は",
    ". Schools should avoid sending sensitive learner information unless it is genuinely required and appropriate to share.": "に基づいて取り扱います。本当に必要で、共有することが適切な場合を除き、学習者の機微な情報は送らないでください。",
    "Chapter X": "第X章",
    "Communication, changes and what happens when circumstances move.": "連絡、変更、状況が変わった場合の対応。",
    "What if the school's needs change during the assignment?": "担当期間中に学校の必要内容が変わった場合はどうなりますか？",
    "Englishire should be informed. A modest practical adjustment may be straightforward; a substantial change in timetable, location, learner group or responsibility may require the arrangement to be reconsidered.": "Englishireへお知らせください。小さな実務調整で対応できる場合もありますが、時間割、所在地、学習者のグループ、担当業務の大きな変更は、手配の再検討が必要になることがあります。",
    "How should concerns be communicated?": "懸念事項はどのように伝えればよいですか？",
    "Promptly, clearly and in proportion to the matter. A concern is easier to address whilst the relevant details remain current.": "問題の大きさに応じて、速やかに、明確にお伝えください。関係する情報が新しいうちの方が対応しやすくなります。",
    "May the school provide updated materials?": "学校から更新した教材を提供できますか？",
    "Certainly. Updated materials, objectives or notes should be supplied in sufficient time for the teacher to use them properly.": "はい。更新した教材、目標、メモは、講師が適切に使える時間を残して共有してください。",
    "What if the absence lasts longer than expected?": "欠勤が予定より長引いた場合はどうなりますか？",
    "Further dates may be considered, though an extension is not automatic. Availability, timetable changes and the continuing responsibilities should be reviewed and confirmed.": "追加の日程を検討できますが、自動的に延長されるわけではありません。講師の空き状況、時間割の変更、継続する担当業務を確認し、改めて確定します。",
    "Chapter XI": "第XI章",
    "After the Assignment": "担当終了後",
    "Handover, feedback and the value of preserving what was learned.": "引き継ぎ、フィードバック、担当中に得た情報を残すこと。",
    "Should the teacher provide a handover?": "講師は引き継ぎを行いますか？",
    "Where relevant, yes. The appropriate handover may range from a brief note concerning work completed to a fuller record of learner progress, homework, materials and outstanding matters.": "必要な場合は行います。実施した内容の短い記録から、学習者の進捗、宿題、教材、未完了事項の詳しい記録まで、ご依頼に合った引き継ぎを行います。",
    "May a school provide feedback?": "学校からフィードバックを伝えられますか？",
    "Certainly. Clear and fair feedback is useful and may assist with future arrangements.": "はい。明確で公平なフィードバックは、今後の手配の改善に役立ちます。",
    "Can an assignment be extended?": "ご依頼を延長できますか？",
    "Potentially, yes. An extension depends upon availability and should be discussed and confirmed rather than assumed.": "はい、検討できます。延長は講師の空き状況によるため、自動的に継続せず、相談して確定します。",
    "Can the same teacher be requested again?": "同じ講師を再度希望できますか？",
    "A school may certainly ask. Whether the same teacher can return depends upon availability and the nature of the new requirement.": "はい、ご希望をお伝えいただけます。同じ講師が再度対応できるかは、空き状況と新しいご依頼内容によって決まります。",
    "Why maintain contact after a successful assignment?": "担当が無事に終わった後も連絡を続ける利点は何ですか？",
    "A prior understanding of the school, timetable and expectations can make a future enquiry more straightforward, particularly where cover requirements recur.": "学校、時間割、期待事項を事前に理解していると、特に代講が繰り返し必要になる場合、次のお問い合わせをより円滑に進められます。",
    "Chapter XII · When We May Decline": "第XII章・ご依頼をお断りする場合",
    "Occasionally, no is the more professional answer.": "専門的な判断として、お断りすることが適切な場合があります。",
    "Declining an assignment does not suggest that the requirement is unimportant. It means that Englishire is not satisfied the work can be undertaken to an appropriate standard under the circumstances presented.": "ご依頼をお断りすることは、必要性が低いという意味ではありません。提示された状況では、適切な水準で実施できるとEnglishireが判断できないという意味です。",
    "A prompt and honest answer is preferable to an uncertain promise which later places the school, teacher or learners in difficulty.": "後から学校、講師、学習者を困らせる不確実な約束より、早い段階で正直に回答する方が適切です。",
    "Essential information is unavailable": "判断に必要な情報が不足している場合",
    "The assignment cannot be understood sufficiently to make a responsible decision.": "責任ある判断をするために十分な内容を把握できない場合。",
    "No suitably matched teacher is free": "適合する講師を確保できない場合",
    "Availability alone does not establish suitability.": "空き状況だけでは、適合性を判断できません。",
    "The journey is not dependable": "確実な移動を見込めない場合",
    "Punctual attendance must remain realistic in ordinary conditions.": "通常の交通状況で、時間どおりの到着を現実的に見込める必要があります。",
    "The work requires different expertise": "別の専門性が必要な場合",
    "Specialist expectations deserve an appropriately experienced teacher.": "専門性の高い内容には、適切な経験を持つ講師が必要です。",
    "The arrangement cannot meet the required standard": "必要な基準を満たす手配ができない場合",
    "Urgency should not compel a promise that cannot be honoured properly.": "急ぎであっても、適切に履行できない約束をするべきではありません。",
    "Clear answers are valuable. Clear boundaries are equally so.": "明確な回答と同じくらい、対応できる範囲を明確にすることも重要です。",
    "The principles beneath these answers are described in": "これらの回答の基礎となる原則は",
    ". The process by which an enquiry becomes an assignment is explained in": "に記載しています。お問い合わせが正式なご依頼になるまでの流れは",
    ". Together, those pages provide the fuller context for the practical guidance collected here.": "で説明しています。両ページを合わせて、このページの実務案内をより詳しく理解できます。",
    "Should a Question Remain": "ご不明な点がある場合",
    "Tell us the circumstances. We will consider them directly.": "状況をお知らせください。Englishireが個別に確認します。",
    "Please include the school location, requested dates, timetable, learner age groups and the nature of the temporary teaching requirement.": "学校所在地、ご希望の日程、時間割、学習者の年齢層、短期の授業支援として必要な内容をお知らせください。",
    "Questions page actions": "よくあるご質問ページの操作",
    "A teacher inviting answers from pupils in a classroom": "教室で生徒に回答を促す講師",
    "Questions page chapters": "よくあるご質問の章一覧",
    "A comprehensive reference for schools considering Englishire temporary teacher cover, including enquiries, suitability, preparation, lessons, administration and follow-up.": "Englishireの英語講師代講を検討する学校向けに、お問い合わせ、講師の適合性、準備、授業、事務手続き、担当後の確認を詳しくご案内します。",
    "Questions About Temporary English Teacher Cover | Englishire": "英語講師の代講・短期手配に関するご質問 | Englishire",
    "Questions schools quite reasonably ask about temporary English teacher cover in Tokyo, answered with clarity and proper qualification.": "東京の学校から英語講師の代講についてよく寄せられる質問に、条件を含めて明確にお答えします。",
    "Englishire questions concerning temporary English teacher cover": "Englishireの英語講師代講に関するよくあるご質問",
    "A clear reference concerning schools, teachers, lessons, assignments and temporary English teacher cover in Tokyo.": "東京の学校、講師、授業、ご依頼、英語講師の短期代講について明確にご案内します。",
}
