"""Exact Japanese translations for the first half of the Questions page."""

TRANSLATIONS = {
    "Questions Schools Ask About Teacher Cover | Englishire": "英語講師の代講について学校からよく寄せられるご質問 | Englishire",
    "Questions Schools Quite Reasonably Ask": "学校からよく寄せられるご質問",
    "Clear answers, properly qualified.": "明確にお答えし、条件がある場合は正確にお伝えします。",
    "A practical reference for schools considering temporary English teacher cover in Tokyo.": "東京都内で英語講師の代講・短期手配を検討している学校向けの実務的なご案内です。",
    "The questions below concern the service, the process, teacher suitability, lessons, administration and what schools may reasonably expect before, during and after an assignment.": "以下では、サービス内容、ご利用の流れ、講師の適合性、授業、事務手続き、ご依頼の前・期間中・終了後に学校が期待できることを説明します。",
    "Find a Question": "質問を探す",
    "A useful answer should provide clarity without pretending every situation has a simple conclusion.": "役立つ回答とは、すべての状況に簡単な結論があるように見せるのではなく、分かっていることと条件を明確にするものです。",
    "How to Read This Page": "このページの読み方",
    "General guidance should clarify, not overpromise.": "一般的な案内は、過度に約束するのではなく、判断材料を明確にするためのものです。",
    "A school asking about one morning of cover is not presenting the same requirement as a school seeking several weeks of recurring lessons. The age of the learners, the timetable, the journey, the materials and the responsibilities involved may alter the answer considerably.": "午前中だけの代講と、数週間にわたる定期授業では、ご依頼内容が異なります。学習者の年齢、時間割、移動条件、教材、担当業務によって、回答は大きく変わることがあります。",
    "The guidance on this page therefore describes the usual Englishire approach. It explains what may be possible, what information is commonly required and where a matter must be considered individually.": "そのため、このページではEnglishireの通常の考え方をご案内します。対応できる可能性、一般に必要な情報、個別判断が必要な事項を説明します。",
    "Where another page gives the fuller explanation, a reference is provided. The service page explains what Englishire offers,": "より詳しい説明が別のページにある場合は、そのページをご案内します。サービスページではEnglishireの提供内容を説明し、",
    "describes the process and": "では手配の流れを、",
    "sets out the principles beneath those decisions.": "では判断の基礎となる原則を示しています。",
    "An answer on this page is guidance. An assignment becomes definite only when it has been expressly reviewed and confirmed.": "このページの回答は一般的なご案内です。ご依頼は、内容を個別に確認し、明確な確定連絡を行った時点で正式に成立します。",
    "The Reference": "質問項目",
    "Find the matter nearest to your enquiry.": "ご相談内容に最も近い項目をご覧ください。",
    "Each chapter may be read independently. Together, they provide the fullest practical account of the service.": "各章は個別に読めます。全体を通して、サービスの実務内容を詳しくご案内します。",
    "Purpose, scope and approach": "目的・対象・考え方",
    "Before Contact": "お問い合わせの前に",
    "Notice, information and early introductions": "連絡時期・必要情報・事前のご紹介",
    "Duration, recurring work and availability": "期間・定期代講・空き状況",
    "Schools and Learners": "学校と学習者",
    "Settings, ages and programmes": "教育環境・年齢層・プログラム",
    "Teachers": "講師",
    "Suitability, briefing and conduct": "適合性・事前説明・職務上の行動",
    "Lessons": "授業",
    "Plans, materials and continuity": "授業計画・教材・継続性",
    "Review and Confirmation": "内容確認と手配の確定",
    "What happens after an enquiry": "お問い合わせ後の流れ",
    "Practical Matters": "実務上の事項",
    "Travel, arrival and school procedures": "移動・到着・学校の手順",
    "Administration": "料金・変更・情報管理",
    "Fees, changes, records and privacy": "料金・変更・記録・プライバシー",
    "During the Assignment": "担当期間中",
    "Communication, changes and support": "連絡・変更・支援",
    "Afterwards": "担当終了後",
    "Handover, extensions and future cover": "引き継ぎ・延長・今後の代講",
    "Boundaries and professional judgement": "対応範囲と専門的判断",
    "Chapter I": "第I章",
    "The organisation, its purpose and the nature of the service.": "Englishireの目的とサービス内容。",
    "What does Englishire do?": "Englishireはどのようなサービスを提供していますか？",
    "Englishire provides temporary English teacher cover for schools and education providers throughout Tokyo. The service is intended for absences, recruitment gaps, additional capacity, leave, events and other circumstances in which lessons require a capable teacher for a limited period.": "Englishireは、東京都内の学校や教育機関に英語講師の代講・短期手配を提供します。講師の欠勤、採用までの空白期間、授業数の増加、休暇、イベントなど、一定期間、適切な講師が必要な場合を対象としています。",
    "See": "詳しくは",
    "for the fuller service description.": "のサービス説明をご覧ください。",
    "Why does temporary teacher cover matter?": "短期の講師代講はなぜ重要ですか？",
    "Proper temporary cover protects continuity whilst a school deals with the wider staffing matter. It allows lessons to continue without forcing a hurried permanent appointment or leaving existing colleagues to absorb every affected class.": "適切な短期代講は、学校が人員体制の問題に対応している間も授業の継続を守ります。常勤採用を急いだり、影響を受けるすべての授業を既存の職員だけで負担したりせずに済みます。",
    "Is Englishire a permanent recruitment agency?": "Englishireは常勤講師の人材紹介会社ですか？",
    "The principal service described on this website is temporary teacher cover. Temporary cover and permanent recruitment serve different purposes and should not be presented as though they were interchangeable.": "このサイトでご案内している主なサービスは、講師の代講・短期手配です。短期代講と常勤採用は目的が異なり、同じサービスとして扱うべきではありません。",
    "Where does Englishire work?": "Englishireはどの地域に対応していますか？",
    "Englishire can consider enquiries across Tokyo and, where practical, nearby areas. The address, nearest station, timetable and realistic journey must be reviewed before an assignment can be accepted.": "東京都内全域と、実務上対応可能な近隣地域のご相談を検討します。ご依頼を引き受ける前に、住所、最寄り駅、時間割、現実的な移動経路を確認します。",
    "What principles guide the service?": "サービスはどのような原則に基づいていますか？",
    "The central principles include suitability before convenience, preparation before placement, communication before assumption and respect for the established school.": "主な原則は、利便性より適合性、配置より先に準備、思い込みより先に連絡と確認、学校が築いてきた方針への敬意です。",
    "They are set out in full in": "詳しくは",
    "Chapter II": "第II章",
    "Before Contacting Englishire": "Englishireへお問い合わせいただく前に",
    "Notice, preparation and what a school should gather in advance.": "連絡時期、事前準備、学校から共有いただきたい情報。",
    "How much notice should a school provide?": "どのくらい前までに連絡すればよいですか？",
    "As much notice as circumstances reasonably allow. More notice generally provides more options, particularly where the timetable is complex, the journey is substantial or the assignment requires particular experience.": "状況が許す限り早めにご連絡ください。時間割が複雑な場合、移動距離が長い場合、特定の経験が必要な場合は、早いほど対応できる選択肢が増えます。",
    "Are urgent enquiries welcome?": "急ぎの問い合わせもできますか？",
    "Yes. Sudden illness and family emergencies rarely provide courteous notice. Urgency, however, does not remove the need to understand the location, timetable, learners and essential responsibilities.": "はい。突然の病気や家族の緊急事態は、十分な連絡時間を与えてくれるとは限りません。ただし、急ぎであっても、所在地、時間割、学習者、主な担当業務の確認は必要です。",
    "May a school introduce itself before cover is needed?": "代講が必要になる前に学校について連絡してもよいですか？",
    "Certainly. A prior introduction can be useful, particularly where a school expects recurring requirements or has a timetable that benefits from advance understanding.": "はい。定期的な代講が想定される学校や、事前に時間割を理解しておくと有効な学校では、早めのご紹介が役立ちます。",
    "What information is most useful at first contact?": "最初の問い合わせで、どの情報が特に役立ちますか？",
    "The school name, address, nearest station, requested dates, reporting time, lesson timetable, learner ages, class sizes, lesson format, materials and any particular requirements.": "学校名、住所、最寄り駅、ご希望の日程、到着時刻、授業時間割、学習者の年齢、クラス人数、授業形式、教材、その他のご要望です。",
    "What if some information is not yet known?": "まだ分からない情報がある場合はどうすればよいですか？",
    "Send what is available and identify what remains uncertain. Englishire can then explain which details are essential before the arrangement can be reviewed or confirmed.": "現時点で分かる情報を送り、未確認の点を明記してください。検討または確定の前に、どの情報が不可欠かをEnglishireからお伝えします。",
    "The full sequence is described in": "詳しい手順は",
    "Chapter III": "第III章",
    "The likely duration, shape and continuity of an assignment.": "ご依頼の期間、形、必要な継続性。",
    "Yes. Cover may concern a single day, several consecutive days, recurring weekly lessons or a longer temporary period, subject to suitability and availability.": "はい。講師の適合性と空き状況に応じて、1日だけ、連続する数日間、毎週の定期授業、より長い期間の短期手配を検討できます。",
    "How long may an assignment last?": "どのくらいの期間まで依頼できますか？",
    "There is no single standard duration. Longer assignments usually require fuller arrangements concerning materials, learner progress, reporting, communication and handover.": "一律の期間はありません。期間が長いご依頼では、教材、学習者の進捗、報告、連絡、引き継ぎについて、より詳しい取り決めが必要になります。",
    "Can Englishire help during a recruitment gap?": "常勤講師の採用までの期間も依頼できますか？",
    "Potentially, yes. Temporary cover can allow the school to continue lessons whilst conducting permanent recruitment with the care that appointment deserves.": "はい、検討できます。短期代講を利用することで、学校は授業を継続しながら、常勤講師の採用を慎重に進められます。",
    "Can the same teacher return for recurring cover?": "定期代講で同じ講師に継続して依頼できますか？",
    "This may be possible and is often desirable where continuity matters. It depends upon the teacher's availability, the timetable and whether the assignment remains substantially as first agreed.": "可能な場合があり、継続性が重要なときには望ましいこともあります。講師の空き状況、時間割、ご依頼内容が当初の合意から大きく変わっていないかによって判断します。",
    "Does an enquiry guarantee that cover is available?": "問い合わせれば、代講を必ず手配できますか？",
    "No. An enquiry begins the review process. Cover is confirmed only where the assignment has been understood and a suitable teacher is available.": "いいえ。お問い合わせは検討の開始です。ご依頼内容を把握し、適切な講師が対応可能な場合にのみ代講を確定します。",
    "Chapter IV": "第IV章",
    "The environments, age groups and programmes which may be considered.": "対象となる教育環境、年齢層、プログラム。",
    "Which kinds of organisation may enquire?": "どのような教育機関が問い合わせできますか？",
    "Englishire can consider enquiries from language schools, private and international programmes, after-school education providers, academies, corporate programmes and related educational organisations.": "語学学校、私立・国際教育プログラム、放課後教育事業者、各種アカデミー、企業向けプログラム、その他の教育機関からのご相談を検討します。",
    "Which age groups may be supported?": "どの年齢層に対応できますか？",
    "Children, teenagers, university-age learners and adults may all be considered. The age group matters because the same teacher is not necessarily suitable for every classroom.": "子ども、中高生、大学生年代、成人に対応を検討できます。同じ講師がすべての年齢層に適しているとは限らないため、年齢は重要な判断材料です。",
    "Does Englishire support children's programmes?": "子ども向けプログラムにも対応できますか？",
    "Potentially, yes. Young learner classes require warmth, pace, clear boundaries and sensible classroom command. Suitability should be considered with particular care.": "はい、検討できます。子どものクラスには、親しみやすさ、テンポ、明確なルール、適切な授業運営が必要なため、講師の適合性を特に慎重に判断します。",
    "Does Englishire support adult or specialist programmes?": "成人向けや専門プログラムにも対応できますか？",
    "Potentially, yes. The learner profile, aims, materials and expected teaching approach must first be understood.": "はい、検討できます。まず、学習者の状況、目的、教材、期待される指導方法を確認します。",
    "Why is the school environment relevant?": "なぜ学校の環境を確認するのですか？",
    "Every school has its own routines, expectations and manner of communicating with learners, parents and staff. A temporary teacher should support that environment rather than arrive determined to replace it.": "学校ごとに、日常の手順、期待事項、学習者・保護者・職員との連絡方法が異なります。短期講師は、それを自分の方法に置き換えるのではなく、既存の環境を支えるべきです。",
    "Chapter V": "第V章",
    "Suitability, briefing and the conduct expected within the school.": "講師の適合性、事前説明、学校内で求められる行動。",
    "How does Englishire assess teacher suitability?": "Englishireは講師の適合性をどのように判断しますか？",
    "Englishire assesses suitability in relation to learner ages, lesson format, school setting, timetable, journey, duration and the responsibilities of the assignment. Availability is necessary, but it is not the whole answer.": "学習者の年齢、授業形式、学校環境、時間割、移動条件、期間、担当業務に照らして判断します。空き状況は必要ですが、それだけでは決まりません。",
    "May a school request particular experience?": "特定の経験を持つ講師を希望できますか？",
    "Yes. Genuine requirements concerning age groups, lesson types, qualifications or specialist experience should be explained at the outset. Such requirements may affect availability.": "はい。年齢層、授業の種類、資格、専門経験について実際に必要な条件がある場合は、最初にお知らせください。条件によっては空き状況に影響します。",
    "What should the teacher know before arrival?": "講師は到着前に何を知っておくべきですか？",
    "The teacher should understand the address, nearest station, reporting point, timetable, learner groups, objectives, materials, dress expectations and relevant school procedures.": "住所、最寄り駅、受付場所、時間割、学習者のグループ、授業目標、教材、服装、関係する学校の手順を理解しておく必要があります。",
    "Should a temporary teacher follow the school's methods?": "短期講師は学校の指導方法に従いますか？",
    "Yes, where those methods have been explained and are appropriate to the assignment. The teacher enters an established environment and should support its routines rather than impose a personal system upon it.": "はい。学校の方法が説明され、ご依頼に適している場合はそれに従います。短期講師は既存の環境に入り、個人的な方法を押しつけるのではなく、学校の日常を支えます。",
    "What professional standards are expected?": "講師にはどのような職務基準を求めますか？",
    "Punctuality, preparation, appropriate dress, sensible communication, respectful conduct, confidentiality and proper attention to learners are fundamental expectations.": "時間厳守、準備、適切な服装、分かりやすい連絡、敬意ある行動、守秘義務、学習者への十分な配慮を基本とします。",
    "for the fuller account.": "で詳しく説明しています。",
    "Chapter VI": "第VI章",
    "Lessons and Materials": "授業と教材",
    "Plans, objectives, resources and continuity between teachers.": "授業計画、目標、教材、講師間の継続性。",
    "Should the school provide lesson plans?": "学校から授業計画を提供する必要がありますか？",
    "Where lesson plans already exist, they are extremely useful. They help the temporary teacher preserve the direction of the course and avoid unnecessary repetition.": "既存の授業計画があれば、非常に役立ちます。短期講師がコースの方向性を保ち、不必要な繰り返しを避けられます。",
    "What if no full lesson plan exists?": "詳しい授業計画がない場合はどうなりますか？",
    "The school should provide the clearest available account of the objective, materials, work already completed and what the lesson should achieve. Any preparation expected from the teacher should be discussed before confirmation.": "授業目標、教材、すでに終えた内容、今回の授業で達成したいことを、分かる範囲でできるだけ明確にお知らせください。講師に準備を求める場合は、確定前に相談します。",
    "Who supplies teaching materials?": "教材は誰が用意しますか？",
    "This depends upon the assignment. Schools commonly provide textbooks, worksheets, plans or access to existing resources. Any expectation that the teacher should create or bring materials must be stated clearly.": "ご依頼によって異なります。通常は学校から教科書、ワークシート、授業計画、既存教材へのアクセスを提供していただきます。講師が教材を作成または持参する必要がある場合は、明確にお知らせください。",
    "Can the teacher continue work already begun?": "すでに始まっている授業内容を続けられますか？",
    "Yes, provided sufficient information is supplied concerning what has been completed, what should follow and any work the returning teacher will expect to receive.": "はい。終えている内容、次に進める内容、復帰する講師へ引き継ぐべき成果物について、十分な情報があれば対応できます。",
    "Can homework, assessment or lesson reports be included?": "宿題、評価、授業報告も依頼できますか？",
    "Potentially, yes. The expectations and time required should be explained before the assignment is confirmed, particularly where cover extends beyond a single day.": "はい、検討できます。特に1日を超える代講では、求める内容と必要な時間を確定前に共有してください。",
}
