"""Reviewed translations for source strings identified by the strict coverage gate."""

TRANSLATIONS = {
    "Understanding Japanese Learners": "日本の学習者を理解する",
    "The temporary teacher's responsibility is not to arrive with a universal formula. One arrives to understand the environment, to respect what the school has already built and to support it with confidence.": "短期講師の役割は、どの教室にも同じ方法を当てはめることではありません。現場を理解し、学校がすでに築いてきたものを尊重し、自信を持って支えるために教室へ入ります。",
    "One arrives not to reinvent the classroom, but to serve it.": "教室を作り替えるためではなく、その教室を支えるために担当します。",
    "An enquiry is not well served by a promise made before the work can be understood. There are occasions when declining an assignment is the more responsible decision.": "ご依頼内容を把握する前の約束は、学校のためになりません。責任ある判断として、ご依頼をお断りする方が適切な場合があります。",
    "Essential information about the school, timetable or learners cannot be provided.": "学校、時間割、学習者に関する重要な情報をご提供いただけない場合。",
    "Travel or access arrangements make punctual arrival insufficiently dependable.": "移動経路や入館方法により、時間どおりの到着を十分に見込めない場合。",
    "The educational demands fall outside the appropriate experience of the available teacher.": "授業上の要件が、対応可能な講師の適切な経験範囲を超える場合。",
    "Expectations cannot reasonably be met within the time or terms proposed.": "提示された時間または条件では、求められる内容を合理的に満たせない場合。",
    "Accepting the work would compromise another confirmed responsibility or the standard of the assignment itself.": "ご依頼を引き受けることで、別の確定済み業務または今回の担当自体の水準を損なう場合。",
    "A declined assignment is not a judgement upon the school. It is simply an acknowledgement that confidence is better preserved by honesty than by a convenient assurance which may later prove unsound.": "ご依頼をお断りすることは、学校を評価することではありません。後に実行できないと分かる都合のよい確約よりも、正直な回答の方が信頼を守れるという判断です。",
    "What We Shall Never Do": "Englishireが行わないこと",
    "Certain shortcuts are not worth taking.": "避けるべき近道があります。",
    "A clear boundary is often more useful than an extravagant promise.": "大げさな約束より、対応範囲を明確にする方が役立ちます。",
    "Promise cover merely to secure an enquiry": "問い合わせをつなぎ止めるためだけに代講を約束する",
    "Every assignment depends upon suitability and availability. We will not confirm what cannot be delivered properly.": "すべてのご依頼は、講師の適合性と空き状況によって決まります。適切に実施できない手配を確定することはありません。",
    "Place convenience above suitability": "適合性より利便性を優先する",
    "A teacher's free diary is not, by itself, a sufficient reason to place that person in a particular classroom.": "講師の予定が空いているというだけでは、その人を特定の教室に配置する十分な理由にはなりません。",
    "Treat temporary cover as careless recruitment": "短期の代講を安易な採用のように扱う",
    "Temporary teaching and permanent recruitment serve different purposes. One should not be misrepresented as the other.": "短期の授業担当と常勤採用は目的が異なります。一方を他方であるかのように説明するべきではありません。",
    "Disregard the school's established culture": "学校が築いてきた文化を軽視する",
    "A temporary teacher is there to support the school, not to impose a personal system upon it.": "短期講師は学校を支えるために担当します。個人的な方法を押しつけるためではありません。",
    "Treat pupils as timetable entries": "生徒を時間割上の一枠として扱う",
    "Every class contains individuals whose confidence, progress and experience deserve proper consideration.": "どのクラスにも、自信、学習の進み方、これまでの経験に適切な配慮を必要とする一人ひとりの学習者がいます。",
    "Before the timetable is sent.": "時間割をお送りいただく前に。",
    "What information should the school provide?": "学校からどのような情報を伝えればよいですか？",
    "Read the Englishire Standard": "Englishireの基準を読む",
    "We notice the timetable": "時間割を具体的に確認します",
    "We notice the learners": "学習者を一人ひとり見ます",
    "We notice the school": "学校の文化と手順を理解します",
    "We notice what has not yet been explained": "まだ説明されていない点にも気づきます",
    "Children, teenagers, adults and specialist learners do not arrive with identical aims or expectations.": "子ども、中高生、成人、専門目的の学習者では、学ぶ目的も期待も同じではありません。",
    "The reason for studying English should influence the manner in which it is taught.": "英語を学ぶ理由に応じて、適切な教え方も変わるべきです。",
    "Schools entrust temporary teachers with far more than a vacant hour in the timetable.": "学校が短期講師に託すものは、時間割の空いた一時間だけではありません。",
    "To the school": "学校に対する責任",
    "We owe clear communication, realistic expectations and respect for the organisation's established procedures and culture.": "明確な連絡、現実的な期待事項、学校が築いてきた手順と文化への敬意を大切にします。",
    "To the learner": "学習者に対する責任",
    "We owe purposeful teaching, calm conduct and recognition that a change of teacher should not make the school day feel careless.": "目的のある授業、落ち着いた行動、講師が替わっても学校の一日を安易なものにしない配慮を大切にします。",
    "To the teacher": "講師に対する責任",
    "We owe sufficient information, a proper briefing and an honest account of the assignment before responsibility is accepted.": "講師が責任を引き受ける前に、十分な情報、適切な事前説明、ご依頼内容の正確な説明を提供します。",
    "Clarity should precede confirmation": "確定より先に内容を明確にする",
    "Dates, times, location, learners, lesson format, materials and expectations should be understood before an assignment is agreed.": "日程、時間、所在地、学習者、授業形式、教材、期待事項を把握してからご依頼に合意します。",
    "Urgency should not disguise uncertainty": "急ぎであっても不明点を隠さない",
    "Where information is incomplete, the uncertainty should be acknowledged rather than concealed beneath a convenient assurance.": "情報が不完全な場合は、都合のよい確約で覆い隠さず、未確認であることを明確にします。",
    "A temporary teacher should respect what already exists": "短期講師は、学校がすでに築いているものを尊重する",
    "The task is to support the school's routines, relationships and educational aims, not to arrive determined to replace them with a personal system.": "役割は、学校の日常手順、人間関係、教育目標を支えることです。個人的な方法に置き換えることではありません。",
    "Professionalism is generally quiet": "専門性は、日々の落ち着いた行動に表れる",
    "It is found in punctuality, preparation, sensible communication, confidentiality and composed classroom conduct rather than theatrical promises.": "専門性は、大げさな約束ではなく、時間厳守、準備、適切な連絡、守秘義務、落ち着いた授業運営に表れます。",
    "There are occasions when Englishire must decline": "Englishireがお断りしなければならない場合がある",
    "An assignment should be declined where it cannot be undertaken suitably, punctually or with the level of preparation the circumstances require.": "ご依頼に適した形、時間どおりの到着、状況に必要な準備水準を確保できない場合は、お断りするべきだと考えています。",
    "Tell us about the school, its learners and the circumstances in which temporary English teacher cover might prove useful.": "学校の概要、学習者、英語講師の代講・短期手配が役立つ可能性のある状況をお知らせください。",
    "Privacy Policy | Englishire": "プライバシーポリシー | Englishire",
    "Cookie Policy | Englishire": "Cookieポリシー | Englishire",
    "Terms of Service | Englishire": "利用規約 | Englishire",
}
