"""Exact Japanese translations for Service Standards."""

TRANSLATIONS = {
    "Service Standards | Englishire": "サービス方針 | Englishire",
    "Clear expectations before an assignment begins.": "ご依頼が始まる前に、双方の条件と期待事項を明確にします。",
    "These standards explain how Englishire responds to enquiries, agrees commercial terms, protects learners and manages temporary teacher cover.": "この方針では、Englishireがお問い合わせにどう対応し、取引条件をどう合意し、学習者の安全をどう守り、講師の代講・短期手配をどう運営するかを説明します。",
    "They are intended to make the working relationship practical and transparent. An enquiry begins a review; it does not reserve a teacher or create a confirmed assignment.": "学校との業務関係を実務的で透明なものにするための方針です。お問い合わせは検討の開始であり、講師の確保や正式な手配の成立を意味しません。",
    "Last reviewed:": "最終確認日：",
    "22 July 2026": "2026年7月22日",
    "The standards": "方針一覧",
    "1. Response standards": "1. 回答に関する方針",
    "2. Commercial framework": "2. 料金・取引条件",
    "3. Confirmation and changes": "3. 確定・キャンセル・変更",
    "4. Safeguarding": "4. 安全管理",
    "5. Information handling": "5. 情報の取扱い",
    "6. Assignment practice": "6. ご依頼の実施",
    "7. Concerns and incidents": "7. 懸念事項・事故・フィードバック",
    "Response standards": "回答に関する方針",
    "Englishire aims to acknowledge a complete enquiry within one business day. Urgent requests are prioritised, but the speed of a reply may depend on the information supplied, travel practicalities and the need to confirm teacher suitability and availability.": "必要事項がそろったお問い合わせには、原則として1営業日以内に受領連絡を行うことを目指します。急ぎのご相談は優先しますが、回答までの時間は、共有された情報、移動条件、講師の適合性と空き状況の確認によって異なる場合があります。",
    "Acknowledgement is not confirmation of cover. Englishire will state clearly when an assignment has been accepted and what further action is required.": "受領連絡は代講の確定ではありません。ご依頼を引き受けた時点と、その後に必要な対応をEnglishireから明確にお伝えします。",
    "Commercial framework": "料金・取引条件",
    "Fees are quoted for the particular assignment after the timetable, location, preparation requirements and other material details have been reviewed.": "料金は、時間割、所在地、必要な準備、その他の重要事項を確認した後、ご依頼ごとに見積もります。",
    "The quotation will identify the agreed teaching work and any stated travel, preparation, tax or additional cost.": "見積書には、合意した授業業務と、明示する交通費、準備費、税金、追加費用を記載します。",
    "No payment obligation arises merely from submitting an enquiry.": "お問い合わせを送っただけで、支払い義務は生じません。",
    "Payment timing and invoicing details are provided before the assignment is confirmed.": "支払時期と請求方法は、ご依頼を確定する前にご案内します。",
    "Material additions to the timetable, duties, location or preparation may require a revised quotation.": "時間割、担当業務、所在地、準備内容に重要な追加がある場合は、見積りを変更することがあります。",
    "Confirmation, cancellation and changes": "確定・キャンセル・変更",
    "An assignment is confirmed only when Englishire has accepted it in writing and the school has accepted the stated terms. Until then, availability may change.": "Englishireが書面でご依頼を受諾し、学校が提示条件を受け入れた時点で正式に確定します。それまでは講師の空き状況が変わる可能性があります。",
    "Cancellation and change terms will be supplied before confirmation and will reflect the timing and practical effect of the change. Englishire will not rely on undisclosed charges.": "キャンセル・変更条件は確定前に提示し、変更の時期と実務上の影響を反映します。事前に開示していない費用を請求の根拠にはしません。",
    "Safeguarding and professional boundaries": "安全管理と職務上の境界",
    "The school retains its ordinary duty of care and responsibility for its safeguarding procedures, site rules and emergency arrangements. Englishire expects relevant policies and reporting routes to be made available before teaching begins.": "学校は通常の安全配慮義務を負い、安全管理手順、施設内規則、緊急時対応について責任を持ちます。授業開始前に、関係する方針と報告経路をEnglishireおよび講師へ共有してください。",
    "Communication with learners must remain within school-authorised channels and professional boundaries.": "学習者との連絡は、学校が承認した経路を用い、職務上の適切な境界を守ります。",
    "Photography, recording and personal-device use must follow the school’s rules and applicable consent requirements.": "写真撮影、録音、個人端末の使用は、学校の規則と必要な同意条件に従います。",
    "Information about health, behaviour or additional needs should be limited to what is necessary for safe and appropriate teaching.": "健康、行動、追加の配慮に関する情報は、安全で適切な授業に必要な範囲に限定してください。",
    "Englishire may decline or discontinue an assignment where conditions appear unsafe, unlawful or materially different from those agreed.": "安全でない、法令に反する、または合意内容と大きく異なる状況である場合、Englishireはご依頼をお断りまたは中止することがあります。",
    "Information handling": "情報の取扱い",
    "Schools should not place unnecessary sensitive information about learners, families or staff in the initial enquiry form. Necessary information can be shared through an appropriate agreed channel after the assignment has been reviewed.": "最初のお問い合わせフォームには、学習者、家族、職員に関する不要な機微情報を記載しないでください。必要な情報は、ご依頼の確認後に、合意した適切な方法で共有できます。",
    "Englishire handles enquiry information in accordance with the": "お問い合わせ情報は、",
    "Assignment practice": "ご依頼の実施",
    "Before the assignment, the school should provide the confirmed timetable, learner groups, lesson objectives, materials, arrival instructions, named contact and relevant emergency information.": "担当開始前に、確定した時間割、学習者のグループ、授業目標、教材、到着方法、担当者名、関係する緊急情報を学校から共有してください。",
    "Englishire will review the whole assignment rather than treating availability alone as evidence of suitability. Significant changes must be communicated promptly and may require renewed agreement.": "Englishireは、空き状況だけを適合性の根拠にせず、ご依頼全体を確認します。重要な変更は速やかに共有し、改めて合意が必要になる場合があります。",
    "Concerns, incidents and feedback": "懸念事項・事故・フィードバック",
    "Immediate safety concerns should be reported through the school’s emergency or safeguarding procedure first. Englishire should then be informed at": "差し迫った安全上の問題は、まず学校の緊急時または安全管理の手順に従って報告してください。その後、Englishireへ",
    "as soon as reasonably possible.": "可能な限り速やかにお知らせください。",
    "Other concerns, corrections or service feedback may also be sent to that address. Reports are considered individually and should include enough factual information to allow a proper review.": "その他の懸念事項、訂正、サービスへのフィードバックも同じメールアドレスへお送りいただけます。個別に確認するため、適切な検討に必要な事実情報を含めてください。",
    "Begin an Enquiry": "問い合わせる",
    "Provide the assignment details currently available.": "現時点で分かるご依頼内容をお知らせください。",
    "Englishire will review the requirement before confirming what can properly be offered.": "Englishireが必要事項を確認したうえで、適切に提供できる内容を確定します。",
    "Service Standards sections": "サービス方針の項目",
    "Englishire response standards, commercial framework, safeguarding expectations and assignment practices for temporary English teacher cover in Tokyo.": "東京の学校向け英語講師代講について、Englishireの回答方針、料金・取引条件、安全管理、ご依頼の実施方法を説明します。",
}
