"""Reviewed Japanese translations for human-readable structured data."""

TRANSLATIONS = {
    "Considered temporary English teacher cover for schools and education providers throughout Tokyo.": "東京都内の学校・教育機関向けに、ご依頼内容を丁寧に確認したうえで英語講師の代講・短期手配を提供します。",
    "How Englishire Teacher Cover Works": "Englishireの講師代講のご利用の流れ",
    "The considered process Englishire follows from a school's first enquiry through review, confirmation, preparation, teaching and final handover.": "学校からの最初のお問い合わせから、内容確認、確定、事前準備、授業、最終の引き継ぎまで、Englishireが丁寧に進める手順です。",
    "Tell us about your school": "学校についてお知らせください",
    "Provide the school location, dates, timetable, learner ages, class sizes, lesson format and assignment requirements.": "学校所在地、日程、時間割、学習者の年齢、クラス人数、授業形式、ご依頼内容をお知らせください。",
    "We consider the assignment": "ご依頼内容を確認します",
    "Englishire reviews the timetable, travel, lesson expectations, duration and teacher suitability.": "Englishireが時間割、移動条件、授業内容、期間、講師の適合性を確認します。",
    "Availability is confirmed": "対応可否を確認します",
    "Cover is confirmed only when a suitable teacher is available and the assignment can be undertaken properly.": "適切な講師が対応可能で、ご依頼を責任を持って実施できる場合にのみ代講を確定します。",
    "The teacher prepares": "講師が事前準備を行います",
    "The teacher receives the relevant school, lesson, learner and arrival information.": "講師に、学校、授業、学習者、到着・受付に関する必要な情報を共有します。",
    "The teacher arrives": "講師が学校へ到着します",
    "The teacher reports to the school, follows the agreed arrangements and conducts the lessons.": "講師は学校へ到着を報告し、合意した手配に従って授業を行います。",
    "The school is supported": "学校を支援します",
    "Any practical questions or changes are addressed through clear communication during the assignment.": "担当期間中の実務上の質問や変更には、明確な連絡を通じて対応します。",
    "The assignment is handed over": "担当内容を引き継ぎます",
    "Relevant lesson information, changes and further cover requirements are reviewed at the conclusion of the assignment.": "担当終了時に、授業情報、変更事項、追加の代講が必要かどうかを確認します。",
    "The Englishire Standard: Principles for Professional Teacher Cover in Japanese Schools": "Englishireの基準：日本の学校における専門的な講師代講の原則",
    "A considered standard for professional temporary English teacher cover in Japanese schools.": "日本の学校で専門的な英語講師の代講・短期手配を行うための、慎重に定めた基準です。",
    "Questions Schools Ask About Englishire Teacher Cover": "Englishireの講師代講について学校からよく寄せられるご質問",
    "A comprehensive reference for schools considering temporary English teacher cover in Tokyo.": "東京で英語講師の代講・短期手配を検討している学校向けの詳しいご案内です。",
    "Englishire provides temporary English teacher cover for schools and education providers throughout Tokyo, subject to assignment suitability and teacher availability.": "Englishireは、ご依頼への適合性と講師の空き状況に応じて、東京都内の学校・教育機関へ英語講師の代講・短期手配を提供します。",
    "No. An enquiry begins the review process. Cover is confirmed only when the assignment has been understood and a suitable teacher is available.": "いいえ。お問い合わせは内容確認の開始です。ご依頼を把握し、適切な講師が対応可能な場合にのみ代講を確定します。",
    "As much notice as circumstances reasonably allow. Urgent enquiries are welcome, though additional notice generally provides more options.": "状況が許す限り早めにご連絡ください。急ぎのご相談も受け付けていますが、早めにご連絡いただくほど対応できる選択肢は増えます。",
    "Yes. Assignments may range from a single day to recurring or longer temporary cover, subject to suitability and availability.": "はい。講師の適合性と空き状況に応じて、1日だけ、定期的な代講、より長い期間の短期手配を検討できます。",
    "Englishire assesses suitability in relation to learner ages, lesson format, school setting, timetable, location, duration and the responsibilities of the assignment.": "Englishireは、学習者の年齢、授業形式、学校環境、時間割、所在地、期間、担当業務に照らして講師の適合性を判断します。",
    "What should a temporary teacher know before arrival?": "短期講師は到着前に何を知っておくべきですか？",
    "The teacher should understand the location, reporting arrangements, timetable, learner groups, lesson objectives, materials and relevant school procedures.": "講師は、所在地、到着・受付方法、時間割、学習者のグループ、授業目標、教材、関係する学校の手順を理解しておく必要があります。",
    "Where lesson plans already exist, they are extremely useful. Where they do not, the school should provide a clear account of objectives, materials and work already completed.": "既存の授業計画があれば非常に役立ちます。ない場合は、授業目標、教材、すでに終えている内容を学校から明確に共有してください。",
    "Englishire should be informed promptly. Material changes may affect teacher suitability, availability or the terms of the original arrangement.": "重要な変更がある場合は、速やかにEnglishireへお知らせください。講師の適合性、空き状況、当初の合意条件に影響することがあります。",
    "Potentially, yes. Any extension depends upon availability and should be discussed and confirmed rather than assumed.": "はい、検討できます。延長は講師の空き状況によるため、自動的に継続せず、相談して確定します。",
    "Why might Englishire decline an assignment?": "Englishireがご依頼をお断りするのはどのような場合ですか？",
    "Englishire may decline where essential information is unavailable, no suitably matched teacher is free, travel is unreliable, expectations fall outside appropriate expertise or the work cannot be undertaken to a proper standard.": "必要な情報が不足している場合、適合する講師を確保できない場合、確実な移動を見込めない場合、必要な専門性の範囲を超える場合、または適切な水準で実施できない場合は、ご依頼をお断りすることがあります。",
    "Request Temporary English Teacher Cover": "英語講師の代講・短期手配を依頼する",
    "Englishire provides considered temporary English teacher cover for schools and education providers across Tokyo.": "Englishireは、東京都内の学校・教育機関向けに、ご依頼内容を丁寧に確認したうえで英語講師の代講・短期手配を提供します。",
    "Englishire Service Standards": "Englishireのサービス方針",
    "Response, commercial, safeguarding and assignment standards for Englishire temporary teacher cover.": "Englishireの講師代講・短期手配に関する、回答、取引条件、安全管理、ご依頼の実施基準です。",
}
