"""Exact Japanese translations for the Teacher Cover page."""

TRANSLATIONS = {
    "Cover the timetable without lowering the standard.": "教育の質を保ちながら、時間割を維持します。",
    "Considered temporary English teacher cover for schools facing absence, recruitment gaps, timetable changes and additional demand.": "講師の欠勤、採用までの空白期間、時間割の変更、授業需要の増加に対応する、学校向け英語講師の代講・短期手配です。",
    "Englishire exists to preserve the continuity of education whilst schools take the time required to make sound decisions. Whether cover is needed for a single day or a considerably longer assignment, the work begins with a proper understanding of the school, the learners and the lessons concerned.": "Englishireは、学校が必要な検討を行い、適切な判断を下すまでの間も教育を継続できるよう支援します。1日だけの代講でも、より長い期間のご依頼でも、まず学校、学習者、対象となる授業を正確に把握することから始めます。",
    "What We Consider": "確認する事項",
    "Tokyo focused": "東京を中心に対応",
    "Assignments are considered across Tokyo and nearby areas.": "東京都内および近隣地域のご依頼を、移動条件を含めて個別に検討します。",
    "A temporary teacher leads a classroom lesson. Proper briefing allows cover to support the lesson, the learners and the routines already established by the school.": "短期で担当する講師が教室で授業を進めています。適切な事前説明があれば、学校が築いてきた授業、学習者への対応、日常の手順を維持しながら代講できます。",
    "A Published Standard": "明文化された基準",
    "Professional teacher cover begins long before a teacher enters the classroom.": "専門的な代講手配は、講師が教室に入る前の確認と準備から始まります。",
    "Every temporary assignment is considered according to the principles set out in": "すべての短期のご依頼は、次に示す原則に基づいて検討します。",
    "The Englishire Standard": "Englishireの基準",
    ". The document describes how we approach suitability, preparation, continuity, professional conduct and the responsibilities owed to each school.": "この文書では、講師の適合性、事前準備、学習の継続、職務上の行動、学校に対する責任について、Englishireの考え方を説明しています。",
    "It exists because temporary cover should not depend upon assumption. Schools should be able to understand the judgement behind an arrangement, as well as the practical service itself.": "短期の代講を思い込みで手配しないために、この基準を公開しています。学校には、実際のサービス内容だけでなく、手配の根拠となる判断も理解していただけるようにします。",
    "Suitability before availability.": "空き状況より適合性を優先します。",
    "Preparation protects the classroom.": "事前準備が授業の安定を守ります。",
    "Continuity before convenience.": "利便性より学習の継続を優先します。",
    "The Quiet Machinery of a School": "学校を静かに動かす仕組み",
    "Every school relies upon a timetable.": "どの学校も、時間割によって一日を運営しています。",
    "A timetable is not merely a collection of lesson times and room numbers. It is a carefully arranged sequence of people, places and expectations which allows the school day to proceed with quiet efficiency.": "時間割は、授業時間と教室番号を並べただけのものではありません。人、場所、役割、期待を慎重に組み合わせ、学校の一日を滞りなく進めるための仕組みです。",
    "When everything unfolds as intended, very little attention is paid to it. Teachers arrive. Pupils arrive. Lessons begin. The school simply gets on with the business of education.": "すべてが予定どおりに進んでいるとき、その仕組みが意識されることはほとんどありません。講師が到着し、生徒が来校し、授業が始まり、学校はいつもどおり教育を行います。",
    "Schools, however, are living organisations rather than perfectly engineered machines. A teacher becomes unwell. A family emergency demands immediate attention. Recruitment takes rather longer than anticipated. Enrolment grows more quickly than the teaching team.": "しかし、学校は完全に設計された機械ではなく、人が動かす組織です。講師が体調を崩すことも、家族の緊急事態に対応しなければならないこともあります。採用が予定より長引いたり、講師体制が整うより早く受講者が増えたりすることもあります。",
    "The timetable remains entirely unmoved by such inconveniences. Tomorrow morning still arrives. The pupils still appear. The lessons still require a teacher.": "そうした事情があっても、時間割は待ってくれません。翌朝は予定どおり訪れ、生徒は来校し、授業には講師が必要です。",
    "It is precisely for those moments that Englishire exists.": "Englishireは、まさにそのような場面に対応するためにあります。",
    "What Temporary Cover Means": "短期の代講が果たす役割",
    "Breathing room, properly arranged.": "学校が適切な判断をするための時間を、責任を持って確保します。",
    "Temporary teacher cover is sometimes mistaken for a hurried attempt to place any available individual in front of a classroom. It should be nothing of the sort.": "短期の代講は、予定が空いている人を急いで教室に立たせることだと思われがちです。しかし、本来そのような手配であってはなりません。",
    "Proper cover allows lessons to continue whilst the school deals with the wider staffing matter carefully. It protects continuity without pretending that a temporary arrangement should replace thoughtful permanent recruitment.": "適切な代講があれば、学校が人員体制の問題を慎重に検討している間も授業を継続できます。短期手配を常勤採用の代わりにするのではなく、採用を丁寧に進めるための時間を確保します。",
    "A rushed appointment made under pressure may create difficulties which endure for months. A sensible temporary assignment, by contrast, gives the school time to recruit properly, interview carefully and preserve its standards in the meantime.": "切迫した状況で採用を急ぐと、その判断による問題が何か月も続くことがあります。適切な短期手配を利用すれば、学校は教育の質を保ちながら、採用と面接を慎重に進められます。",
    "It is not a careless substitution": "単に空きを埋める代講ではありません",
    "Availability alone does not make a teacher suitable for a particular classroom.": "予定が空いているというだけで、その講師が特定の授業に適しているとは限りません。",
    "It is not permanent recruitment": "常勤講師の採用ではありません",
    "Temporary cover supports the school whilst longer-term decisions are made with the care they deserve.": "短期の代講は、学校が長期的な人員判断を慎重に行う間の授業運営を支えます。",
    "It is not a lowering of standards": "教育水準を下げるものではありません",
    "A school's expectations should not change merely because the member of staff has.": "担当者が替わったという理由だけで、学校の教育方針や期待水準を変えるべきではありません。",
    "It is a practical interval": "次の判断までを支える実務的な手配です",
    "Proper cover preserves lessons, protects confidence and provides time for sound judgement.": "適切な代講は授業を継続し、学校の信頼を守り、適切な判断に必要な時間を確保します。",
    "When Schools Call Upon Us": "学校からご相談いただく場面",
    "The first lesson of the day has an unfortunate habit of arriving before every staffing problem has been solved.": "人員の問題が解決するのを待たずに、その日の最初の授業は始まります。",
    "There is little benefit in pretending that illness, family emergencies or travel disruption respect school timetables. They do not.": "病気、家族の緊急事態、交通障害が学校の時間割に合わせて起こることはありません。",
    "Schools frequently discover early in the morning that a teacher will not be arriving. Pupils are already travelling, parents remain unaware of the difficulty and lessons begin within hours. Temporary cover exists so the day may proceed with composure rather than panic.": "早朝になって、担当講師が来られないと分かることがあります。生徒はすでに学校へ向かい、保護者はまだ状況を知らず、数時間後には授業が始まります。短期の代講は、学校が慌てずに一日を進めるための手段です。",
    "Recruitment Gaps": "採用までの空白期間",
    "Recruiting well generally requires patience. Recruiting in haste generally requires compromise.": "適切な採用には、通常、時間が必要です。採用を急げば、妥協が生じやすくなります。",
    "A school ought never to feel obliged to appoint the first acceptable candidate merely because Monday's lessons require a teacher. Temporary cover provides the freedom to conduct the permanent search properly.": "週明けの授業に講師が必要だからという理由だけで、最初に条件を満たした候補者を採用する必要はありません。短期の代講を利用することで、常勤講師の採用を適切に進める余裕が生まれます。",
    "Occasionally the difficulty is not absence at all. New classes appear, enrolment increases or the timetable expands beyond the capacity of the existing team.": "問題が欠勤ではない場合もあります。新しいクラスが増え、受講者数が伸び、既存の講師チームだけでは時間割に対応しきれなくなることがあります。",
    "Temporary support allows the school to meet that demand whilst deciding whether the increase represents a passing season or a permanent change.": "短期支援を利用すれば、その増加が一時的なものか恒常的な変化かを見極めながら、目の前の授業需要に対応できます。",
    "Programmes, Trials and Events": "講座・体験授業・イベント",
    "A school may require a teacher for an intensive course, a demonstration lesson, a seasonal programme, an event or a limited series of classes.": "集中講座、体験授業、季節プログラム、イベント、回数限定の授業などで、一定期間だけ講師が必要になることがあります。",
    "Not every short requirement should become a permanent recruitment exercise. A clearly defined temporary assignment may be the altogether more sensible arrangement.": "短期間の必要に対して、常勤採用を行う必要はありません。内容と期間が明確な短期手配の方が、合理的な場合があります。",
    "From Enquiry to Classroom": "お問い合わせから教室まで",
    "A clear sequence, without unnecessary ceremony.": "形式にとらわれず、明確な手順で進めます。",
    "Temporary cover may be urgent. The decisions surrounding it should nevertheless remain orderly.": "代講が急ぎで必要な場合でも、手配に関する判断は順序立てて行います。",
    "The enquiry": "お問い合わせ",
    "The school provides the dates, location, timetable, learners and nature of the requirement.": "学校から、日程、所在地、時間割、学習者、ご依頼の内容を共有していただきます。",
    "The discussion": "確認のやり取り",
    "Any material uncertainties are clarified before assumptions begin to acquire the appearance of fact.": "推測が事実として扱われる前に、手配に影響する不明点を確認します。",
    "The review": "内容の検討",
    "Travel, lesson demands, duration, responsibility and practical feasibility are considered together.": "移動条件、授業内容、期間、担当業務、実務上の実現可能性をまとめて検討します。",
    "The match": "講師との適合性",
    "Availability is examined only alongside suitability for the school, the learners and the work.": "空き状況だけでなく、学校、学習者、担当業務への適合性と合わせて判断します。",
    "The confirmation": "手配の確定",
    "The arrangement is confirmed when its essential terms are understood and can be met properly.": "主要な条件を双方が理解し、適切に履行できると確認できた時点で手配を確定します。",
    "The briefing": "事前説明",
    "The teacher receives the practical and educational information required to arrive prepared.": "講師には、準備を整えて到着するために必要な実務情報と授業情報を共有します。",
    "The assignment": "担当当日・担当期間",
    "The teacher supports the established classroom rather than treating temporary responsibility as licence to reinvent it.": "短期で担当する講師は、独自の方法で授業を作り替えるのではなく、学校が築いてきた授業運営を支えます。",
    "The follow-up": "授業後の確認",
    "Where appropriate, relevant observations and continuing needs are communicated after the work.": "必要に応じて、授業中に確認した事項や今後必要な対応を、担当後に共有します。",
    "Teaching English well in Japan requires more than fluency.": "日本で英語を適切に教えるには、英語力だけでは足りません。",
    "Englishire's work is informed by a thorough understanding of Japanese students and the learning environments in which they study. That understanding has been shaped across a broad range of classrooms throughout Tokyo rather than acquired from theory alone.": "Englishireの手配と授業支援は、日本の学習者と、その学習環境への具体的な理解に基づいています。その理解は、理論だけでなく、東京にある多様な教室での経験を通じて培われてきました。",
    "Some learners are wonderfully eager to speak. Others require time, reassurance and a proper sense that mistakes will be treated as part of learning rather than as a public spectacle.": "積極的に話す学習者もいれば、発言するまでに時間と安心感を必要とする学習者もいます。間違いが人前で責められるものではなく、学習の一部として扱われると感じられることが大切です。",
    "Participation is not always measured by who speaks first or loudest. A thoughtful teacher recognises quiet engagement, builds confidence without embarrassment and creates sufficient order for learners to take genuine linguistic risks.": "参加の度合いは、最初に発言した人や声の大きい人だけで測れるものではありません。適切な講師は、静かな取り組みにも気づき、恥ずかしい思いをさせずに自信を育て、学習者が安心して英語を試せる授業環境を整えます。",
    "Children": "子ども",
    "Young learners often require warmth, pace and energy, though never at the expense of safety, structure or purpose.": "子どもの授業には、親しみやすさ、テンポ、活気が求められます。ただし、安全、授業構成、学習目的を犠牲にしてはなりません。",
    "Teenagers": "中高生",
    "Adolescent learners may need a careful balance of encouragement, academic clarity and respect for their growing independence.": "中高生には、励まし、学習内容の明確さ、成長する自立心への敬意を、適切に組み合わせる必要があります。",
    "Adults": "成人",
    "Adult learners rightly expect their aims, experience and limited time to be taken seriously.": "成人の学習者には、学習目的、これまでの経験、限られた時間を真剣に扱うことが求められます。",
    "Specialist learners": "専門目的の学習者",
    "Examination, professional and private programmes require attention to the particular purpose for which English is being studied.": "試験対策、業務目的、個別プログラムでは、英語を学ぶ具体的な目的に沿った指導が必要です。",
    "ACROSS TOKYO": "東京のさまざまな教育現場で",
    "One city. Many forms of learning.": "一つの都市に、多様な学びの形があります。",
    "A Broad Educational Landscape": "幅広い教育環境",
    "No two corners of English education are quite alike.": "英語教育の現場は、一つとして同じではありません。",
    "We have worked across the varied landscape of English-learning environments in Tokyo: independent language schools, private academies, children's programmes, adult conversation classes, specialist courses, international settings and other educational organisations with their own methods, expectations and cultures.": "Englishireは、東京にある多様な英語教育の現場に関わってきました。独立系の語学学校、各種アカデミー、子ども向けプログラム、成人英会話、専門コース、国際的な教育環境など、それぞれに独自の方法、期待、文化があります。",
    "A lively afternoon class for young children bears little resemblance to an evening programme for working adults. A formal academic environment asks something different of a teacher than a conversational school with a highly personal atmosphere.": "幼い子どもの活気ある午後クラスと、社会人向けの夜間プログラムでは、授業の進め方が大きく異なります。学術的な教育環境で講師に求められることと、個別性の高い英会話スクールで求められることも同じではありません。",
    "The Shape of an Assignment": "ご依頼の期間と形",
    "Temporary does not mean identical.": "短期の手配でも、内容は一律ではありません。",
    "The right arrangement depends upon the nature of the need.": "適切な手配は、学校が必要としている内容によって異なります。",
    "Single-Day Cover": "1日だけの代講",
    "A short assignment may be arranged for an isolated absence, event or particular day in the timetable.": "単発の欠勤、イベント、時間割上の特定の日に合わせて、1日だけの代講を検討できます。",
    "Brief does not mean unprepared. Even one day deserves clear information, suitable materials and an understanding of the learners concerned.": "期間が短くても、準備を省くことはできません。1日だけでも、明確な情報、適切な教材、担当する学習者への理解が必要です。",
    "Several Consecutive Days": "連続する数日間の代講",
    "A period of illness, leave or temporary disruption may require a teacher to maintain continuity across a run of lessons.": "病気、休暇、一時的な運営上の事情により、数日間にわたって同じ流れで授業を継続する講師が必要になることがあります。",
    "Where possible, consistency becomes especially valuable, as the teacher can build upon the previous lesson rather than beginning afresh each day.": "可能であれば同じ講師が継続して担当することで、毎日最初から始めるのではなく、前回の授業を踏まえて進められます。",
    "Recurring Weekly Cover": "毎週の定期代講",
    "A school may need temporary assistance on particular days or during particular periods of the week.": "特定の曜日や週の一部の時間帯に、継続的な短期支援が必要になることがあります。",
    "Such assignments require dependable scheduling and a clear division of responsibility between the temporary teacher and the wider school team.": "このようなご依頼では、確実なスケジュール管理と、短期講師と学校側チームの明確な役割分担が必要です。",
    "Longer Temporary Placements": "より長い期間の短期手配",
    "Recruitment gaps, extended leave or developing programmes may call for support over a more substantial period.": "採用までの空白期間、長期休暇、立ち上げ途中のプログラムでは、比較的長い期間の支援が必要になることがあります。",
    "Longer cover requires careful attention to reporting, continuity, materials, learner progress and communication with the school.": "期間が長くなるほど、報告、授業の継続、教材、学習者の進捗、学校との連絡をより丁寧に行う必要があります。",
    "Preparing for Cover": "代講に向けた準備",
    "A clear briefing is one of the finest forms of welcome.": "明確な事前説明は、講師を迎えるうえで最も有効な準備の一つです。",
    "A capable teacher can respond sensibly to the unexpected, but no school benefits from withholding information that could readily have been supplied in advance.": "経験のある講師は予期しない状況にも対応できますが、事前に共有できた情報が伝わっていないことで学校が得をすることはありません。",
    "The most effective temporary assignments begin with a concise, practical briefing. It need not be ceremonial. It simply should tell the teacher what matters.": "円滑な短期手配は、簡潔で実用的な事前説明から始まります。形式ばった文書は必要ありませんが、講師が知るべき重要事項は明確に伝える必要があります。",
    "Arrival information": "到着・受付情報",
    "Building access, reporting point, contact person, start time and any security or sign-in arrangements.": "建物への入り方、受付場所、担当者、到着時刻、入館・記帳などの手順。",
    "Lesson information": "授業情報",
    "Timetable, rooms, materials, lesson objectives, homework and any work already completed.": "時間割、教室、教材、授業目標、宿題、すでに終えている学習内容。",
    "Learner information": "学習者情報",
    "Ages, approximate levels, class sizes and any particular needs the teacher should understand.": "年齢、おおよそのレベル、クラス人数、講師が把握すべき配慮事項。",
    "School expectations": "学校の方針・期待事項",
    "Dress, conduct, classroom routines, reporting and communication procedures.": "服装、振る舞い、授業中の手順、報告方法、連絡方法。",
    "A standard rather than an assumption.": "思い込みではなく、明確な基準に基づいて判断します。",
    "Schools place considerable trust in the people invited into their classrooms. That trust deserves a clear account of how temporary assignments are considered and conducted.": "学校は、教室に迎える人に大きな信頼を寄せます。その信頼に応えるため、短期のご依頼をどのように検討し、実施するかを明確に示します。",
    "Suitability should always take precedence over availability.": "講師の空き状況よりも、学校と授業への適合性を優先します。",
    "sets out the principles governing preparation, professional conduct, continuity, communication and our relationship with schools. It is intended to make the basis of our decisions visible—not merely the outcome of them.": "は、準備、職務上の行動、学習の継続、連絡、学校との関係に関する原則を定めています。結果だけでなく、判断の根拠も学校に分かるようにするための文書です。",
    "When We May Decline": "ご依頼をお断りする場合",
    "Professional judgement occasionally requires a courteous no.": "専門的な判断として、丁寧にお断りしなければならない場合があります。",
    "Common Questions": "よくあるご質問",
    "A few practical matters schools quite reasonably wish to know.": "学校からよく寄せられる実務上の質問にお答えします。",
    "Can Englishire provide cover for one day?": "1日だけの代講も依頼できますか？",
    "Yes. Assignments may range from a single day to recurring or extended temporary cover, subject to suitability and availability.": "はい。講師の適合性と空き状況に応じて、1日だけ、毎週の定期代講、より長い期間の短期手配を検討できます。",
    "How much notice is required?": "どのくらい前までに連絡すればよいですか？",
    "More notice generally provides more options, though urgent enquiries are welcome. The answer depends upon the dates, times, location and nature of the assignment.": "早めにご連絡いただくほど、対応できる選択肢は増えます。急ぎのご相談も受け付けていますが、対応可否は日程、時間、所在地、ご依頼内容によって異なります。",
    "Does an enquiry guarantee a teacher?": "問い合わせれば、必ず講師を確保できますか？",
    "No. Every requirement must be reviewed before cover can be confirmed. We will not promise an arrangement before we know it can be carried out properly.": "いいえ。ご依頼内容を確認し、適切に実施できると判断した後に代講を確定します。対応できる見込みを確認する前に、手配を約束することはありません。",
    "Please include the location, nearest station, dates, lesson times, learner ages, approximate levels, class sizes, lesson format, materials and any particular requirements.": "所在地、最寄り駅、日程、授業時間、学習者の年齢、おおよそのレベル、クラス人数、授業形式、教材、その他のご要望をお知らせください。",
    "Can the same teacher cover several lessons?": "同じ講師に複数の授業を依頼できますか？",
    "Potentially, yes. The timetable, travel, lesson types and overall assignment must first be considered.": "可能です。ただし、時間割、移動条件、授業の種類、ご依頼全体を確認したうえで判断します。",
    "Does Englishire provide permanent recruitment?": "Englishireは常勤講師の採用支援も行っていますか？",
    "The principal service described here is temporary teacher cover. Any separate recruitment assistance would be discussed distinctly and without ambiguity.": "このページでご案内している主なサービスは、英語講師の代講・短期手配です。別途採用支援を行う場合は、短期手配とは明確に区別してご説明します。",
    "View All Questions": "よくあるご質問をすべて見る",
    "Schools are welcome to introduce themselves before cover is required. A prior understanding of the school, its timetable and the sort of assignment which may one day arise can make future requests easier to assess.": "代講が必要になる前でも、学校についてご連絡いただけます。学校の特徴、時間割、将来想定されるご依頼を事前に把握しておくと、実際のご相談をより正確に検討できます。",
    "Tell us about your school, its learners and the circumstances in which temporary cover might prove useful.": "学校の概要、学習者、短期の代講が必要になり得る状況についてお知らせください。",
    "A Final Word": "最後に",
    "Difficulty is inevitable. Disorder need not be.": "予期しない問題は起こります。しかし、混乱まで避けられないわけではありません。",
    "Every school encounters unforeseen circumstances. The important question is not whether disruption arises, but whether it is met with clarity, preparation and sound professional judgement.": "どの学校にも予期しない状況は起こります。重要なのは、問題が起こるかどうかではなく、明確な確認、十分な準備、適切な専門判断によって対応できるかどうかです。",
    "Englishire provides temporary English teacher cover so that lessons may continue whilst schools address the wider staffing matter with the care it deserves.": "Englishireは、学校が人員体制の問題を慎重に検討している間も授業を継続できるよう、英語講師の代講・短期手配を提供します。",
    "Proper preparation remains preferable to unnecessary urgency.": "不必要に急ぐより、適切に準備する方が確実です。",
    "The class remains on the timetable. Let us help keep it there.": "時間割にある授業を、予定どおり実施できるよう支援します。",
    "Send the school location, dates, lesson times, learner age groups and the nature of the teaching support required. We will consider the assignment with proper care.": "学校所在地、日程、授業時間、学習者の年齢層、必要な授業支援の内容をお送りください。ご依頼を丁寧に確認します。",
    "Read how it works": "ご利用の流れを見る",
    "Teacher cover page actions": "講師代講ページの操作",
    "Teacher cover summary": "講師の代講・短期手配の概要",
    "A teacher leading a line of children outside an ornate brick school building": "装飾的なれんが造りの校舎の前で、子どもたちの列を引率する講師",
    "Selected principles": "主な原則",
    "Englishire provides considered temporary English teacher cover for schools, academies and education providers throughout Tokyo.": "Englishireは、東京都内の学校、各種アカデミー、教育機関に対し、ご依頼内容を確認したうえで英語講師の代講・短期手配を提供します。",
    "Considered temporary English teacher cover for Tokyo schools facing absence, recruitment gaps, timetable changes and additional demand.": "講師の欠勤、採用までの空白期間、時間割の変更、授業需要の増加に対応する、東京の学校向け英語講師の代講・短期手配です。",
    "Professional temporary English teachers for schools throughout Tokyo.": "東京都内の学校向けに、適切に準備した英語講師の代講・短期手配を行います。",
}
