"""Exact Japanese translations for the Terms of Service."""

TRANSLATIONS = {
    "Clear expectations make for better working relationships.": "条件と期待事項を明確にすることが、よりよい業務関係につながります。",
    "These terms explain how Englishire considers enquiries, confirms temporary teacher cover and works with schools throughout Tokyo.": "本規約は、Englishireがお問い合わせをどのように検討し、講師の代講・短期手配をどのように確定し、東京都内の学校とどのように業務を行うかを説明します。",
    "Before any assignment begins.": "ご依頼を始める前に。",
    "Englishire believes that professional relationships are strongest when expectations are understood before the first lesson rather than after it. Accordingly, these terms explain how enquiries are reviewed, how assignments become confirmed and the responsibilities shared by both Englishire and the school.": "Englishireは、最初の授業後ではなく授業前に期待事項を共有することで、最も確かな業務関係が築かれると考えています。本規約では、お問い合わせの確認方法、ご依頼が正式に確定するまでの流れ、Englishireと学校がそれぞれ負う責任を説明します。",
    "1. Enquiries": "1. お問い合わせ",
    "An enquiry is an invitation to consider an assignment. It is not, by itself, confirmation that a teacher is available or that cover has been accepted.": "お問い合わせは、ご依頼を検討するための連絡です。それだけで講師が対応可能であることや、代講を引き受けたことが確定するものではありません。",
    "2. Availability": "2. 講師の空き状況",
    "Availability depends upon the assignment, timetable, location, learner groups and other practical considerations. Availability should never be assumed until Englishire confirms the arrangement.": "対応可否は、ご依頼内容、時間割、所在地、学習者のグループ、その他の実務条件によって異なります。Englishireが手配を確定するまでは、対応可能であると判断しないでください。",
    "3. Confirmation": "3. 手配の確定",
    "An assignment becomes confirmed only when Englishire expressly agrees the dates, timetable and principal arrangements.": "Englishireが日程、時間割、主な手配内容に明確に合意した時点で、ご依頼が正式に確定します。",
    "4. Information Provided by the School": "4. 学校から提供いただく情報",
    "Schools should provide accurate information concerning the location, nearest station, timetable, learner age groups, lesson format, teaching materials, safeguarding arrangements and any other matters reasonably required to understand the assignment.": "学校は、所在地、最寄り駅、時間割、学習者の年齢層、授業形式、教材、安全管理の手順、その他ご依頼を把握するために合理的に必要な事項について、正確な情報を提供してください。",
    "5. Teacher Responsibilities": "5. 講師の責任",
    "Teachers are expected to conduct themselves professionally, arrive punctually, prepare appropriately, respect school procedures, maintain confidentiality and represent Englishire with courtesy.": "講師には、職務上適切に行動し、時間どおりに到着し、必要な準備を行い、学校の手順を尊重し、秘密を保持し、Englishireを代表する立場として礼儀正しく対応することを求めます。",
    "6. Changes": "6. 変更",
    "Should the timetable, location or nature of the assignment change, Englishire should be informed promptly so that the revised arrangements may be considered properly.": "時間割、所在地、ご依頼の性質が変わる場合は、変更後の手配を適切に検討できるよう、速やかにEnglishireへお知らせください。",
    "7. Cancellation": "7. キャンセル",
    "Where cancellation becomes necessary, the school should notify Englishire as soon as reasonably practicable. Any applicable arrangements will depend upon what has previously been agreed.": "キャンセルが必要になった場合は、合理的に可能な限り速やかにEnglishireへお知らせください。適用される条件は、事前に合意した内容によります。",
    "8. Fees": "8. 料金",
    "Fees, expenses and any related administrative matters are agreed before an assignment is confirmed unless expressly stated otherwise.": "別途明示しない限り、料金、経費、関係する事務事項は、ご依頼を確定する前に合意します。",
    "9. Liability": "9. 責任",
    "Englishire endeavours to provide its services with reasonable care and professional judgement. Nothing within these terms excludes liability where exclusion would be unlawful.": "Englishireは、合理的な注意と専門的な判断をもってサービスを提供するよう努めます。本規約は、法令上免責が認められない責任を除外するものではありません。",
    "10. Governing Law": "10. 準拠法",
    "These terms should be interpreted in accordance with the laws applicable to the services provided and any mandatory legal requirements.": "本規約は、提供するサービスに適用される法令および強行法規に従って解釈されます。",
    "11. Contact": "11. お問い合わせ",
    "Questions concerning these terms are welcome through the": "本規約に関するご質問は、",
    "Our Working Principle": "Englishireの業務原則",
    "We believe that the strongest professional relationships begin with clarity rather than assumption.": "確かな業務関係は、思い込みではなく、条件を明確にすることから始まると考えています。",
    "Should anything within these terms require clarification, we should be delighted to explain it.": "本規約に分かりにくい点がある場合は、Englishireへお問い合わせください。",
    "Questions concerning these terms may be sent through the contact page.": "本規約に関するご質問は、お問い合わせページからお送りください。",
    "Englishire's Terms of Service explain how temporary teacher cover enquiries are considered, confirmed and delivered.": "Englishireの利用規約は、講師の代講・短期手配に関するお問い合わせをどのように検討、確定、実施するかを説明します。",
    "The terms governing temporary English teacher cover enquiries and assignments with Englishire.": "Englishireへの英語講師代講のお問い合わせと正式なご依頼に適用される条件です。",
}
